export const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
export async function accountRequest(path,body,method='POST'){const r=await fetch('/api/'+path,{method,...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'Account request failed.'),{status:r.status});return data;}
export function passwordChange(container,onChanged){const form=node('form',undefined,'panel workflow-panel form-grid');form.append(node('h2','Change your password'),node('p','Use 12–128 characters. Changing your password signs out all your sessions.'));const fields={};for(const [key,label]of [['currentPassword','Current password'],['newPassword','New password']]){const wrap=node('label',label),input=node('input');input.type='password';input.required=true;input.maxLength=128;if(key==='newPassword')input.minLength=12;input.autocomplete=key==='newPassword'?'new-password':'current-password';wrap.append(input);form.append(wrap);fields[key]=input;}const error=node('p');error.setAttribute('role','alert');const save=node('button','Change password','primary');form.append(error,save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await accountRequest('auth/change-password',Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])));for(const i of Object.values(fields))i.value='';onChanged();}catch(e){error.textContent=e.message;save.disabled=false;}};container.append(form);}
export async function renderAccounts(view){const status=await accountRequest('auth/status',undefined,'GET'),demo=status.mode==='device-demo';view.append(node('h1',demo?'Demo accounts':'Your account'));if(!status.configured){view.append(node('p','Local IT must bootstrap the first administrator before accounts can be managed.'));return;}view.append(node('p',demo?'Demo accounts use device-local passwords to demonstrate signing in. The default administrator credentials are public. Do not reuse a real password.':`Signed in as ${status.user.displayName||status.user.username}.`));if(!demo)passwordChange(view,()=>location.reload());if(status.user.role!=='administrator'){view.append(node('p','An account administrator manages access and local password resets.'));return;}
 const directory=await accountRequest('accounts',undefined,'GET');
 function editor(account){const form=node('form',undefined,'panel workflow-panel form-grid');form.append(node('h2',account?'Manage '+account.displayName:(demo?'Create demo profile':'Create account')));const values={username:account?.username||'',displayName:account?.displayName||'',role:account?.role||'coordinator',active:account?.active??true};const controls={};form.append(node('p','Staff accounts are separate from client and professional profiles.'));
 for(const [key,label]of [['username','Username'],['displayName','Display name'],['role','Account permission']]){const wrap=node('label',label),input=node(key==='role'?'select':'input');input.required=true;input.setAttribute('aria-label',label);if(key==='role'){input.append(new Option('Office coordinator','coordinator'),new Option('Account administrator','administrator'));}input.value=values[key];if(key==='username'&&account)input.disabled=true;if(input.tagName==='INPUT')input.maxLength=key==='username'?60:120;wrap.append(input);form.append(wrap);controls[key]=input;}
 if(account){const wrap=node('label','Active account'),input=node('input');input.type='checkbox';input.checked=values.active;wrap.prepend(input);form.append(wrap);controls.active=input;}
 if(!account){const wrap=node('label',demo?'Demo password':'Temporary password'),input=node('input');input.type='password';input.autocomplete='new-password';input.minLength=12;input.maxLength=128;input.required=true;wrap.append(input);form.append(wrap);controls.password=input;form.append(node('p',demo?'Choose a demo-only password of 12–128 characters. Use this username and password to sign back in.':'Share the temporary credential through your approved local process. The user must change it at first sign-in.'));}
 const message=node('p');message.setAttribute('role','alert');const save=node('button',account?'Save account':demo?'Create demo profile':'Create account','primary');form.append(message,save);let requestId=crypto.randomUUID(),pending=null;form.onsubmit=async e=>{e.preventDefault();save.disabled=true;const body=pending??{requestId,displayName:controls.displayName.value,role:controls.role.value,...(account?{version:account.version,active:controls.active.checked}:{username:controls.username.value,password:controls.password.value})};pending=body;for(const control of Object.values(controls))control.disabled=true;try{await accountRequest('accounts'+(account?'/'+account.id:''),body,account?'PUT':'POST');location.reload();}catch(e){message.textContent=e.message;if(e.status){pending=null;requestId=crypto.randomUUID();for(const [key,control]of Object.entries(controls))control.disabled=key==='username'&&Boolean(account);}save.textContent=pending?'Retry same save':account?'Save account':'Create account';save.disabled=false;}};
 if(account){const details=node('details'),summary=node('summary',demo?'Set a demo password':'Set a temporary password');details.append(summary);const reset=node('input');reset.type='password';reset.minLength=12;reset.maxLength=128;reset.autocomplete='new-password';reset.setAttribute('aria-label','New temporary password');const button=node('button','Reset password and revoke sessions','secondary');button.type='button';let resetPending=null;button.onclick=async()=>{if(reset.value.length<12){message.textContent='Use 12–128 characters.';return;}button.disabled=true;resetPending??={requestId:crypto.randomUUID(),version:account.version,password:reset.value};reset.disabled=true;try{await accountRequest('accounts/'+account.id+'/reset-password',resetPending);location.reload();}catch(e){message.textContent=e.message;if(e.status){resetPending=null;reset.disabled=false;}button.textContent=resetPending?'Retry same reset':'Reset password and revoke sessions';button.disabled=false;}};details.append(node('p',demo?'Use only a demo password. The account must sign in again after a reset.':'This signs out the account everywhere and requires a password change at next sign-in.'),reset,button);form.append(details);}
 return form;}
 view.append(editor(null));for(const account of directory.items){const details=node('details',undefined,'panel'),summary=node('summary',`${account.displayName} · ${account.role} · ${account.active?'Active':'Inactive'}`);details.append(summary,editor(account));view.append(details);}
}
