import {seed} from './seed.mjs';
const key='tadsa-web-v1',main=document.querySelector('#content');let data;
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(text,fn)=>{const b=n('button',text,'secondary');b.type='button';b.onclick=fn;return b;};
function save(next){try{localStorage.setItem(key,JSON.stringify(next));data=next;document.querySelector('#storage-status').textContent='Saved on this device.';return true;}catch{document.querySelector('#storage-status').textContent='Storage is unavailable or full. Your changes were not saved.';return false;}}
try{const stored=localStorage.getItem(key);data=stored?JSON.parse(stored):seed();if(!Array.isArray(data.people)||!Array.isArray(data.projects))throw Error();}catch{data=null;main.append(n('h1','Unable to open saved prototype data'),n('p','Use Reset demonstration data below if you want to discard the saved data and start again.'));}
const personName=id=>data.people.find(p=>p.id===id)?.name||'Not assigned';
function clientName(p){return personName(data.clients.find(c=>c.id===data.primaryRecords.find(r=>r.id===p.primaryRecordId)?.clientId)?.personId);}
function render(){if(!data)return;const kind=location.hash==='#people'?'people':'projects';main.replaceChildren(n('h1',kind==='people'?'People':'Projects'),n('p','Explore the workflow using fictional records. Changes stay on this device.','subtitle'));main.append(button(kind==='people'?'New person':'New project',()=>edit(kind)));
const search=n('input');search.type='search';search.placeholder='Find a name, project or reference';search.setAttribute('aria-label','Filter records');main.append(search);const list=n('div',null,'record-list');const tools=n('div',null,'prototype-toolbar');const create=main.querySelector('button');create.className='primary';const label=n('label');label.append(n('span','Search records','field-label'),search);tools.append(label,create);main.append(tools,list);document.querySelectorAll('.sidebar nav a').forEach(a=>{if(a.hash==='#'+kind)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
function draw(){list.replaceChildren();const q=search.value.toLowerCase();for(const record of data[kind].filter(r=>JSON.stringify(r).toLowerCase().includes(q))){const card=n('section',null,'panel');card.append(n('h2',record.name||record.title));if(kind==='people')card.append(n('p',record.role),n('p',[record.email,record.phone].filter(Boolean).join(' · ')));else card.append(n('p',record.reference+' · '+record.status+' · '+clientName(record)),n('p',record.summary),n('p','Technician: '+personName(data.relationships.find(r=>r.projectId===record.id&&r.role==='Technician')?.id)));card.append(button('Edit '+(record.name||record.title),()=>edit(kind,record)),button('Delete '+(record.name||record.title),()=>remove(kind,record)));list.append(card);}if(!list.children.length)list.append(n('p','No matching records.'));}search.oninput=draw;draw();}
function remove(kind,r){if(kind==='people'&&(data.clients.some(c=>c.personId===r.id&&data.primaryRecords.some(pr=>pr.clientId===c.id&&data.projects.some(p=>p.primaryRecordId===pr.id)))||data.relationships.some(rel=>rel.id===r.id))){alert('This person is linked to projects. Reassign or remove those projects before deleting the person.');return;}if(!confirm('Delete '+(r.name||r.title)+' from this device?'))return;const next=structuredClone(data);next[kind]=next[kind].filter(x=>x.id!==r.id);if(kind==='projects'){next.relationships=next.relationships.filter(x=>x.projectId!==r.id);next.audit=next.audit.filter(x=>x.projectId!==r.id);}else next.clients=next.clients.filter(c=>c.personId!==r.id);if(save(next))render();}
function edit(kind,record){main.replaceChildren(n('h1',record?'Edit '+(record.name||record.title):kind==='people'?'New person':'New project'));main.append(n('p','Fields marked Required must be completed. Changes are saved on this device only.','subtitle'));const form=n('form',null,'panel form-grid prototype-form');const inputs={};function field(key,label,value='',values){const l=n('label');l.append(n('span',label,'field-label'));const e=n(values?'select':key==='summary'?'textarea':'input');e.setAttribute('aria-label',label);if(values)for(const[v,t]of values){const o=n('option',t);o.value=v;e.append(o);}e.value=value;e.required=['name','title','clientId'].includes(key);if(e.required)l.querySelector('span').append(n('small',' · Required','required-hint'));if(key==='summary'){l.className='wide-field';e.rows=5;}if(key==='phone')e.type='tel';if(!values)e.maxLength=key==='summary'?2000:200;l.append(e);form.append(l);inputs[key]=e;}
if(kind==='people'){field('name','Full name',record?.name);field('role','Role',record?.role||'Client',['Client','Technician','Occupational therapist','Administrator','Carer','Referrer','Allied-health contact'].map(x=>[x,x]));field('email','Email',record?.email);inputs.email.type='email';field('phone','Phone',record?.phone);if(record&&data.clients.some(c=>c.personId===record.id)){inputs.role.disabled=true;form.append(n('p','Existing client role is retained to preserve links.'));}}
else{field('title','Project title',record?.title);field('clientId','Client',data.primaryRecords.find(r=>r.id===record?.primaryRecordId)?.clientId||'',[['','Choose client'],...data.clients.map(c=>[c.id,personName(c.personId)])]);field('summary','What does the client need?',record?.summary);field('kind','Type',record?.kind||'Assessment',[['Assessment','Assessment'],['Technical','Technical']]);field('status','Status',record?.status||'open',['open','review','closed'].map(x=>[x,x]));field('technician','Technician',data.relationships.find(r=>r.projectId===record?.id&&r.role==='Technician')?.id||'',[['','Not assigned'],...data.people.filter(p=>p.role==='Technician').map(p=>[p.id,p.name])]);}
const submit=n('button','Save','primary');submit.type='submit';const actions=n('div',null,'actions');actions.append(submit,button('Cancel',()=>{if(confirm('Discard unsaved changes?'))render();}));form.append(actions);main.append(form);window.scrollTo(0,0);form.querySelector('input')?.focus({preventScroll:true});form.onsubmit=e=>{e.preventDefault();const next=structuredClone(data),values=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value.trim()]));if(!(values.name||values.title)){alert('Enter a name or title.');return;}const id=record?.id||kind+'-'+crypto.randomUUID();if(kind==='people'){if(!record&&next.people.some(p=>p.name.toLowerCase()===values.name.toLowerCase())&&!confirm('A person with this name exists. Create a separate person?'))return;const p={...record,id,...values};if(record)next.people=next.people.map(x=>x.id===id?p:x);else next.people.push(p);if(p.role==='Client'&&!next.clients.some(c=>c.personId===id))next.clients.push({id:'client-'+crypto.randomUUID(),personId:id});}else{let primary=record?.primaryRecordId;if(!primary||next.primaryRecords.find(r=>r.id===primary)?.clientId!==values.clientId){primary='request-'+crypto.randomUUID();next.primaryRecords.push({id:primary,clientId:values.clientId,reference:'WEB-'+Date.now(),summary:values.summary});}const p={...record,id,title:values.title,summary:values.summary,kind:values.kind,status:values.status,primaryRecordId:primary,reference:record?.reference||'WEB-'+Date.now(),version:(record?.version||0)+1,feedbackRequired:record?.feedbackRequired||false,invoiceRequired:record?.invoiceRequired||false};if(record)next.projects=next.projects.map(x=>x.id===id?p:x);else next.projects.push(p);next.relationships=next.relationships.filter(r=>!(r.projectId===id&&r.role==='Technician'));if(values.technician)next.relationships.push({projectId:id,type:'person',id:values.technician,role:'Technician'});}if(save(next))render();};}
document.querySelector('#reset').onclick=()=>{if(confirm('Erase all prototype changes on this device and restore fictional examples?')&&save(seed()))render();};window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===key)location.reload();});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>document.querySelector('#storage-status').textContent='Offline caching unavailable; online use still works.');
