import {node,action,link,notice,request,field,editor} from './project-care.js';
let weekStart=null;
const localDay=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const move=(day,n)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return localDay(d);};
export async function renderAvailability(view){
 const [technicians,options]=await Promise.all([request('technicians'),request('availability-options')]);
 const calendars=await Promise.all(technicians.items.map(t=>request('availability/'+t.id)));
 if(!weekStart){const today=new Date();weekStart=move(localDay(today),-((today.getDay()+6)%7));}
 view.append(node('h1','Technician availability'),node('p','All technicians, one week at a time. Unrecorded dates mean availability is unknown. Confirm availability before assigning work.','subtitle'));
 const controls=node('div',null,'actions'),board=node('div',null,'availability-board'),forms=node('div');view.append(controls,board,forms);
 const dateState={week:weekStart};const date=field(controls,'Week containing',dateState,'week','date');
 const redraw=()=>{date.value=weekStart;board.replaceChildren();const days=Array.from({length:7},(_,i)=>move(weekStart,i));board.append(node('h2',new Date(weekStart+'T12:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'})));for(let i=0;i<technicians.items.length;i++){const t=technicians.items[i],calendar=calendars[i],row=node('section',null,'panel technician-week');const heading=node('div');heading.append(link(t.name,'person/'+t.id),node('p',calendar.serviceAreas.map(id=>options.serviceAreas.find(a=>a.id===id)?.label||id).join(', ')||'Service areas not recorded','field-help'));row.append(heading);const grid=node('div',null,'calendar-days');for(const day of days){const entry=calendar.entries.find(e=>e.startDate<=day&&e.endDate>=day),cell=action('',()=>edit(t,calendar,entry,day));cell.className='calendar-day '+(entry?.status||'unknown');cell.append(node('strong',new Date(day+'T12:00:00').toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short'})),node('span',entry?({available:'Available',limited:'Limited',unavailable:'Unavailable'}[entry.status]):'Not recorded'));if(entry?.note)cell.append(node('small',entry.note));cell.setAttribute('aria-label',`${t.name}, ${day}: ${entry?.status||'not recorded'}. Edit availability`);grid.append(cell);}row.append(grid);board.append(row);}if(!technicians.items.length)board.append(notice('Add a person with the Technician role to begin.'),link('Add person','new-person'));};
 controls.prepend(action('← Previous week',()=>{weekStart=move(weekStart,-7);redraw();}));controls.append(action('Next week →',()=>{weekStart=move(weekStart,7);redraw();}));date.onchange=()=>{if(!date.value)return;const day=new Date(date.value+'T12:00:00');weekStart=move(date.value,-((day.getDay()+6)%7));redraw();};
 function edit(t,calendar,entry,day){forms.replaceChildren();const heading=node('h2',t.name);heading.tabIndex=-1;forms.append(heading);const initial=entry||{id:null,version:0,startDate:day,endDate:day,status:'available',note:''};editor(forms,'calendar/'+t.id+'/'+(entry?.id||'new'),initial,'Availability dates',(form,d)=>{field(form,'Start date',d,'startDate','date').required=true;field(form,'End date',d,'endDate','date').required=true;field(form,'Availability',d,'status','text',[['available','Available'],['limited','Limited availability'],['unavailable','Unavailable']]);field(form,'Availability note',d,'note','textarea');},`availability/${t.id}/entries`,'POST',d=>Object.fromEntries(['requestId','id','version','startDate','endDate','status','note'].map(k=>[k,d[k]])));
 if(entry){const remove=node('details');remove.append(node('summary','Remove this date range'));forms.append(remove);editor(remove,'calendar-remove/'+entry.id,entry,null,f=>f.append(node('p',`Remove ${entry.startDate} to ${entry.endDate}? These dates will become unknown.`)),`availability/${t.id}/entries/${entry.id}/remove`,'POST',d=>({requestId:d.requestId,version:d.version}));}
 editor(forms,'areas/'+t.id,{version:calendar.version,serviceAreas:[...calendar.serviceAreas]},'Service areas',(form,d)=>{for(const area of options.serviceAreas){const check=field(form,area.label,{checked:d.serviceAreas.includes(area.id)},'checked','checkbox');check.onchange=()=>{d.serviceAreas=check.checked?[...d.serviceAreas,area.id]:d.serviceAreas.filter(x=>x!==area.id);};}},`availability/${t.id}/areas`,'PUT',d=>({requestId:d.requestId,version:d.version,serviceAreas:d.serviceAreas}));heading.focus();forms.scrollIntoView({behavior:'smooth',block:'start'});}
 redraw();
}
