import {validateLifecycleBackup} from './device-lifecycle-validation.mjs';
import {validateCredentials} from './device-credentials.mjs';
import {validateProfileDetailsBackup} from './device-profile-details.mjs';
import {validateProjectDetailsBackup} from './device-project-details.mjs';
import {validateInvoiceReferencesBackup} from './device-invoice-references.mjs';
import {normalise,fail} from './device-model.mjs';
import {validateDeviceFile} from './device-files.mjs';
const STORE='workspace',MAX_BYTES=256*1024*1024,FORMAT='tadsa-device-backup';
const clone=x=>structuredClone(x);
const canonical=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');
const uuid=x=>typeof x==='string'&&/^[a-f\d]{8}-[a-f\d]{4}-[1-5][a-f\d]{3}-[89ab][a-f\d]{3}-[a-f\d]{12}$/i.test(x);
function invalid(message){fail('Backup rejected: '+message,422);}
function object(x){return x!==null&&typeof x==='object'&&!Array.isArray(x);}
const DAY=/^\d{4}-\d{2}-\d{2}$/;
function validDay(value){return typeof value==='string'&&DAY.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
function validInstant(value){return typeof value==='string'&&value.length<60&&Number.isFinite(Date.parse(value));}
function amount(value,label,min=0,max=1000000000){if(!Number.isSafeInteger(value)||value<min||value>max)invalid(label+' is not a valid integer amount.');}
const businessFields=['issuerName','abn','address','contact','paymentTerms','bankDetails','gstMode','gstRateBps','gstConfirmed'];
function validateBusiness(value,snapshot=false){
 if(!object(value)||Object.keys(value).some(k=>![...businessFields,...(snapshot?[]:['version','audit'])].includes(k)))invalid('business settings contain unsupported fields.');
 for(const [key,max]of [['issuerName',200],['abn',11],['address',500],['contact',500],['paymentTerms',1000],['bankDetails',1000]])if(typeof value[key]!=='string'||value[key].length>max)invalid('invalid business '+key+'.');
 if(value.abn&&!/^\d{11}$/.test(value.abn))invalid('business ABN must be eleven digits.');if(!['unconfirmed','not-registered','inclusive','exclusive'].includes(value.gstMode)||typeof value.gstConfirmed!=='boolean')invalid('invalid GST treatment.');amount(value.gstRateBps,'GST rate',0,10000);if(value.gstConfirmed&&value.gstMode==='unconfirmed')invalid('unconfirmed GST cannot be marked confirmed.');
 if(!snapshot){amount(value.version,'Business settings version',1,2147483647);if(!Array.isArray(value.audit)||value.audit.some(x=>!object(x)||!validInstant(x.at)))invalid('invalid business settings history.');}
}
function bounded(x){let text;try{text=JSON.stringify(x);}catch{invalid('data must be JSON.');}if(new TextEncoder().encode(text).byteLength>MAX_BYTES)invalid('file exceeds the 256 MB limit.');return text;}
function exact(input,fields){if(!object(input)||Object.keys(input).length!==fields.length||fields.some(k=>!Object.hasOwn(input,k)))fail('Supply exactly the required backup fields.');if(!uuid(input.requestId))fail('Supply a valid backup request identifier.');}
function atomic(db,keys,callback,write=false){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,write?'readwrite':'readonly'),store=tx.objectStore(STORE),values={};let remaining=keys.length,result,error;const complete=()=>{try{result=callback(values,store);}catch(e){error=e;tx.abort();}};for(const key of keys){const r=store.get(key);r.onsuccess=()=>{values[key]=r.result;if(!--remaining)complete();};}if(!keys.length)complete();tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(error??tx.error??Error('Storage could not commit the backup operation.'));tx.onerror=()=>{};});}
function keys(db){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE),r=tx.objectStore(STORE).getAllKeys();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
const counts=d=>({people:d.people.length,clients:d.clients.length,projects:d.projects.length,organisations:d.organisations.length,notes:Object.values(d.operations).reduce((n,o)=>n+(o.notes?.length||0),0),invoices:Object.values(d.operations).reduce((n,o)=>n+(o.invoices?.length||0),0),attachments:Object.values(d.attachments).reduce((n,a)=>n+a.filter(x=>!x.removed).length,0)});
async function envelope(data){bounded(data);const createdAt=new Date().toISOString(),copy=clone(data);return {format:FORMAT,formatVersion:1,createdAt,dataVersion:copy.schemaVersion,data:copy,sha256:await hash(canonical(copy))};}
function metadata(id,env,name){return {id,name:name||`TADSA-device-${env.createdAt.replace(/[:.]/g,'-')}.json`,createdAt:env.createdAt,size:new TextEncoder().encode(JSON.stringify(env)).byteLength};}
function saveBackup(store,id,env,name){const meta=metadata(id,env,name);store.put(env,'backup:'+id);store.put(meta,'backup-meta:'+id);return meta;}
function safeName(value){if(typeof value!=='string'||!value.trim()||value.length>180||/[\\/<>:"|?*\u0000-\u001f]/.test(value))fail('Use a plain backup filename of at most 180 characters.');return value.trim();}
export async function validateBackup(input){
 bounded(input);let raw;
 if(input?.format===FORMAT){if(input.formatVersion!==1)invalid('unsupported envelope version.');if(!object(input.data)||input.dataVersion!==input.data.schemaVersion||typeof input.sha256!=='string')invalid('missing or inconsistent data version/checksum.');if(await hash(canonical(input.data))!==input.sha256)invalid('checksum does not match the backup contents.');raw=clone(input.data);}
 else if(object(input)&&[3,4,5].includes(input.schemaVersion))raw=clone(input);
 else invalid('expected a TADSA device backup or a version 3/4/5 device export.');
 if(![3,4,5].includes(raw.schemaVersion))invalid('unsupported data schema version.');
 // Reject unusual keys anywhere, before data is used in property-indexed maps.
 const stack=[raw];while(stack.length){const x=stack.pop();if(!x||typeof x!=='object')continue;for(const [k,v]of Object.entries(x)){if(['__proto__','prototype','constructor'].includes(k))invalid('unsupported object key.');if(v&&typeof v==='object')stack.push(v);}}
 if(raw.schemaVersion===5)raw.primaryRecords??=[];
 const collections=['people','clients','primaryRecords','projects','relationships','audit','organisations'];for(const key of collections)if(!Array.isArray(raw[key]))invalid(key+' must be a list.');
 const sets={};for(const table of ['people','clients','primaryRecords','projects','organisations']){sets[table]=new Set();for(const row of raw[table]){if(!object(row)||typeof row.id!=='string'||row.id.length>100||!/^[a-z]+-[a-z\d-]+$/i.test(row.id)||sets[table].has(row.id))invalid(table+' contains an invalid or duplicate identifier.');sets[table].add(row.id);}}
 const ref=(table,id,description)=>{if(!sets[table].has(id))invalid(description+' refers to a missing '+table+' record.');};
 const text=(value,label,max=2000)=>{if(typeof value!=='string'||value.length>max)invalid(label+' is not valid text.');};
 const version=(value,label)=>{if(!Number.isSafeInteger(value)||value<1)invalid(label+' has an invalid version.');};
 if(raw.applicationSettings!==undefined){const a=raw.applicationSettings;if(!object(a)||Object.keys(a).some(k=>!['version','labourRateCents','currency','appliesTo','audit'].includes(k)))invalid('invalid application settings fields.');version(a.version,'Application settings');amount(a.labourRateCents,'Labour rate',1,10000000);if(a.currency!=='AUD'||a.appliesTo!=='new-projects'||!Array.isArray(a.audit))invalid('invalid application settings.');for(const h of a.audit){if(!object(h)||!validInstant(h.at))invalid('invalid rate history.');amount(h.fromRateCents,'Previous labour rate',1,10000000);amount(h.toRateCents,'New labour rate',1,10000000);}}
 if(raw.businessSettings!==undefined)validateBusiness(raw.businessSettings);
 if(raw.statusEvents!==undefined){if(!Array.isArray(raw.statusEvents))invalid('status events must be a list.');for(const e of raw.statusEvents){if(!object(e))invalid('invalid status event.');ref('projects',e.id,'Status event');if(!validInstant(e.at)||![null,'open','review','closed'].includes(e.fromStatus)||!['open','review','closed'].includes(e.toStatus))invalid('invalid status event date or state.');}}
 for(const p of raw.people){text(p.name,'Person name',120);text(p.email,'Person email',254);text(p.phone,'Person phone',40);if(p.version!==undefined)version(p.version,'Person');if(p.roles!==undefined&&(!Array.isArray(p.roles)||!p.roles.length||p.roles.some(r=>typeof r!=='string')))invalid('person roles must be a non-empty list.');if(p.technician!==undefined&&p.technician!==null&&(!object(p.technician)||!Array.isArray(p.technician.skills)))invalid('invalid technician profile.');}
 if(raw.projectSequence!==undefined)amount(raw.projectSequence,'Project sequence',5702,Number.MAX_SAFE_INTEGER);
 for(const o of raw.organisations){if(o.email!==undefined){text(o.email,'Organisation email',254);if(o.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o.email))invalid('invalid organisation email.');}if(o.category!==undefined)text(o.category,'Organisation category',80);if(o.version!==undefined)version(o.version,'Organisation');text(o.name,'Organisation name',200);text(o.description??'','Organisation description');}
 const clientPeople=new Set();for(const c of raw.clients){ref('people',c.personId,'Client');if(clientPeople.has(c.personId))invalid('multiple client profiles point to the same person.');clientPeople.add(c.personId);if(c.details!==undefined){if(!object(c.details))invalid('invalid client details.');if(c.details.representativePersonId)ref('people',c.details.representativePersonId,'Preferred representative');}}
 for(const r of raw.primaryRecords){ref('clients',r.clientId,'Primary request');text(r.reference,'Primary reference',120);}
 for(const p of raw.projects){if(p.primaryRecordId&&p.legacyPrimaryRecordId&&p.primaryRecordId!==p.legacyPrimaryRecordId)invalid('conflicting archived project links.');if(p.labourRateCents!==undefined)amount(p.labourRateCents,'Project labour rate',1,10000000);if(p.kind!==undefined&&!['Assessment','Technical'].includes(p.kind))invalid('unsupported project kind.');for(const key of ['feedbackRequired','invoiceRequired'])if(typeof p[key]!=='boolean')invalid('invalid project flags.');if(raw.schemaVersion<5){ref('primaryRecords',p.primaryRecordId,'Project');const archived=raw.primaryRecords.find(r=>r.id===p.primaryRecordId);if(p.clientId!==undefined&&p.clientId!==archived.clientId)invalid('Project client conflicts with its archived request.');}else{ref('clients',p.clientId,'Project');const legacy=p.legacyPrimaryRecordId??p.primaryRecordId;if(legacy){ref('primaryRecords',legacy,'Archived project linkage');if(raw.primaryRecords.find(r=>r.id===legacy).clientId!==p.clientId)invalid('Project client conflicts with its archived request.');}}text(p.title,'Project title',120);text(p.reference,'Project reference',120);if(!['open','review','closed'].includes(p.status))invalid('project status is unsupported.');if(p.version!==undefined)version(p.version,'Project');if(p.coordination){const c=p.coordination;if(!Array.isArray(c.requiredSkills))invalid('invalid required skills.');if(c.technicianId)ref('people',c.technicianId,'Technician');if(c.technicianIds!==undefined){if(!Array.isArray(c.technicianIds)||c.technicianIds.length>20||new Set(c.technicianIds).size!==c.technicianIds.length||c.technicianIds.length&&(!c.technicianId||!c.technicianIds.includes(c.technicianId))||!c.technicianIds.length&&c.technicianId)invalid('invalid technician team.');for(const id of c.technicianIds)ref('people',id,'Technician team');}if(c.payerId)ref(c.fundingStatus==='organisation'?'organisations':'people',c.payerId,'Intended payer');}}
 for(const r of raw.relationships){if(!object(r))invalid('invalid relationship.');ref('projects',r.projectId,'Relationship');if(!['person','organisation'].includes(r.type))invalid('unsupported relationship type.');ref(r.type==='person'?'people':'organisations',r.id,'Relationship');text(r.role,'Relationship role',120);}
 for(const a of raw.audit){if(!object(a))invalid('invalid audit event.');ref('projects',a.projectId,'Audit event');}
 if(raw.contacts!==undefined&&!Array.isArray(raw.contacts))invalid('contacts must be a list.');for(const c of raw.contacts??[]){ref('clients',c.clientId,'Contact');ref('people',c.personId,'Contact');}
 for(const key of ['operations','calendars','workPlans','attachments','clientNdis','credentials','lifecycles','replays'])if(raw[key]!==undefined&&!object(raw[key]))invalid(key+' must be an object.');
 validateProfileDetailsBackup(raw);
 validateProjectDetailsBackup(raw);
 validateInvoiceReferencesBackup(raw);
 const invoiceIds=new Map(),invoiceTotals=new Map();
 for(const [id,o]of Object.entries(raw.operations??{})){
  ref('projects',id,'Operations');if(!object(o))invalid('invalid operations.');for(const key of ['actualMinutes','remainingMinutes'])amount(o[key],'Operation minutes',0,600000);
  if(!Array.isArray(o.notes)||!Array.isArray(o.invoices)||!Array.isArray(o.fundingContributors))invalid('invalid operational lists.');
  for(const field of ['assessmentComplete','workApproved','onHold','clientStopped','resumeClientConsent','reviewRequired'])if(typeof o[field]!=='boolean')invalid('invalid operational choice.');
  for(const key of ['approvedBy','approvedOn','fundingExceptionReason'])text(o[key],'Operational '+key);if(o.approvedOn&&!validDay(o.approvedOn))invalid('invalid work approval date.');
  const noteIds=new Set();for(const note of o.notes){if(!object(note)||!uuid(note.id)||noteIds.has(note.id)||!validInstant(note.at))invalid('invalid case note identifier or date.');text(note.text,'Case note',2000);text(note.actor,'Case note author',200);noteIds.add(note.id);}
  for(const c of o.fundingContributors){if(!['client','person','organisation'].includes(c.type))invalid('invalid funding contributor type.');ref(c.type==='client'?'clients':c.type==='organisation'?'organisations':'people',c.id,'Funding contributor');amount(c.amountCents,'Funding contribution',1);}
  const ids=new Set();for(const invoice of o.invoices){
   if(!object(invoice)||!uuid(invoice.id)||ids.has(invoice.id)||!object(invoice.snapshot)||!validInstant(invoice.at))invalid('invalid invoice identifier or date.');text(invoice.number,'Invoice number',150);
   const snap=invoice.snapshot;if(!['client','person','organisation'].includes(snap.payerType))invalid('invalid invoice recipient type.');ref(snap.payerType==='client'?'clients':snap.payerType==='organisation'?'organisations':'people',snap.payerId,'Invoice recipient');
   for(const key of ['projectReference','projectTitle','clientName','payerName'])text(snap[key],'Invoice '+key);if(!['deposit','progress','final'].includes(snap.milestone)||!['separate','nominated'].includes(snap.billingMode))invalid('invalid invoice billing details.');
   if(!Array.isArray(snap.lines)||!snap.lines.length||snap.lines.length>10)invalid('invalid invoice lines.');let lineTotal=0;
   for(const line of snap.lines){if(!object(line))invalid('invalid invoice line.');text(line.description,'Invoice item',200);amount(line.amountCents,'Invoice line amount',1);if(line.quantityMilli!==undefined||line.unitPriceCents!==undefined){amount(line.quantityMilli,'Invoice quantity',1,1000000);amount(line.unitPriceCents,'Invoice unit price',1);if(Math.round(line.quantityMilli*line.unitPriceCents/1000)!==line.amountCents)invalid('invoice line arithmetic is inconsistent.');}lineTotal+=line.amountCents;}
   amount(snap.totalCents,'Invoice total',1);if(snap.business!==undefined)validateBusiness(snap.business,true);if(snap.invoiceDate!==undefined&&!validDay(snap.invoiceDate))invalid('invalid invoice date.');if(snap.billingAddress!==undefined)text(snap.billingAddress,'Billing address',500);
   if(snap.subtotalCents!==undefined||snap.gstCents!==undefined){amount(snap.subtotalCents,'Invoice subtotal');amount(snap.gstCents,'Invoice GST');if(snap.subtotalCents+snap.gstCents!==snap.totalCents)invalid('invoice totals do not add up.');const exclusive=snap.business?.gstConfirmed&&snap.business.gstMode==='exclusive';if((exclusive?snap.subtotalCents:snap.totalCents)!==lineTotal)invalid('invoice line totals do not match its tax treatment.');}else if(snap.totalCents!==lineTotal)invalid('legacy invoice total does not match its items.');
   if(snap.readinessWarnings!==undefined&&(!Array.isArray(snap.readinessWarnings)||snap.readinessWarnings.some(w=>typeof w!=='string')))invalid('invalid invoice warnings.');ids.add(invoice.id);invoiceTotals.set(id+':'+invoice.id,snap.totalCents);
  }invoiceIds.set(id,ids);
 }
 for(const [id,c]of Object.entries(raw.calendars??{})){ref('people',id,'Calendar');if(!object(c)||!Array.isArray(c.entries)||!Array.isArray(c.serviceAreas))invalid('invalid calendar.');amount(c.version,'Calendar version',0,2147483647);const ids=new Set();let previousEnd='';for(const e of [...c.entries].sort((a,b)=>String(a.startDate).localeCompare(String(b.startDate)))){if(!uuid(e.id)||ids.has(e.id)||!validDay(e.startDate)||!validDay(e.endDate)||e.endDate<e.startDate||!['available','limited','unavailable'].includes(e.status)||e.startDate<=previousEnd)invalid('invalid or overlapping calendar entry.');version(e.version,'Calendar entry');text(e.note,'Calendar note',500);previousEnd=e.endDate;ids.add(e.id);}}
 for(const [id,w]of Object.entries(raw.workPlans??{})){
  ref('projects',id,'Work plan');if(!object(w))invalid('invalid work plan.');for(const key of ['ndisApplicable','ndisApproved'])if(w[key]!==undefined&&typeof w[key]!=='boolean')invalid('invalid NDIS choice.');for(const key of ['location','suburb','postcode','serviceArea','ndisApprovedBy','ndisApprovedOn','approvedNumber'])if(w[key]!==undefined)text(w[key],'Work plan '+key,500);if(w.postcode&&!/^\d{4}$/.test(w.postcode))invalid('invalid project postcode.');if(w.ndisApprovedOn&&!validDay(w.ndisApprovedOn))invalid('invalid NDIS approval date.');if(w.payments!==undefined&&!Array.isArray(w.payments))invalid('invalid receipt list.');const receiptIds=new Set(),paid=new Map();
  for(const receipt of w.payments??[]){if(!object(receipt)||!uuid(receipt.id)||receiptIds.has(receipt.id)||!invoiceIds.get(id)?.has(receipt.invoiceId)||!validDay(receipt.receivedOn)||!validInstant(receipt.at))invalid('invalid receipt identifier, invoice or date.');amount(receipt.amountCents,'Receipt amount',1);text(receipt.reference,'Payment reference',200);receiptIds.add(receipt.id);paid.set(receipt.invoiceId,(paid.get(receipt.invoiceId)||0)+receipt.amountCents);if(paid.get(receipt.invoiceId)>invoiceTotals.get(id+':'+receipt.invoiceId))invalid('receipts exceed the invoice total.');}
 }
 for(const [id,n]of Object.entries(raw.clientNdis??{})){ref('clients',id,'NDIS record');if(!object(n))invalid('invalid NDIS record.');amount(n.version,'NDIS version',0,2147483647);if(typeof n.number!=='string'||(n.number&&!/^[0-9 ]{3,30}$/.test(n.number)))invalid('invalid NDIS number.');}
 for(const [id,state]of Object.entries(raw.lifecycles??{})){ref('projects',id,'Lifecycle');validateLifecycleBackup(state);const project=raw.projects.find(p=>p.id===id);if(Boolean(state.closed)!==(project.status==='closed'))invalid('lifecycle closure does not match project status.');}
 for(const [id,value]of Object.entries(raw.credentials??{})){ref('people',id,'Technician credentials');if(value.personId!==id)invalid('credential person does not match its record.');validateCredentials(value);}
 for(const [id,files]of Object.entries(raw.attachments??{})){ref('projects',id,'Attachments');if(!Array.isArray(files))invalid('attachment list is invalid.');const ids=new Set();for(const file of files){if(!uuid(file.id)||ids.has(file.id))invalid('invalid or duplicate attachment ID.');ids.add(file.id);await validateDeviceFile({name:file.name,mime:file.mime,dataBase64:file.dataBase64});if(file.size!==atob(file.dataBase64).length)invalid('attachment size does not match contents.');}if(files.filter(x=>!x.removed).length>20)invalid('a project exceeds the active attachment limit.');}
 if(!Number.isSafeInteger(raw.sequence)||raw.sequence<0)invalid('invalid identifier sequence.');for(const set of Object.values(sets))for(const id of set){const n=id.match(/-(\d+)$/)?.[1];if(n&&Number(n)>raw.sequence)invalid('identifier sequence is behind an existing record.');}
 let data;try{data=normalise(raw);}catch{invalid('data cannot be upgraded safely.');}return data;
}
export async function handleDeviceBackups(db,path,method,input){
 const parts=path.split('/'),[,id,sub,tail]=parts;if(parts[0]!=='backups')return undefined;
 if(method==='GET'&&!id){const metaKeys=(await keys(db)).filter(k=>typeof k==='string'&&k.startsWith('backup-meta:'));return atomic(db,metaKeys,v=>({items:Object.values(v).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),capabilities:{import:true}}));}
 if(method==='GET'&&sub==='download'){if(!uuid(id))fail('Backup not found.',404);const env=await atomic(db,['backup:'+id],v=>v['backup:'+id]);if(!env)fail('Backup not found.',404);await validateBackup(env);const meta=metadata(id,env);return {deviceDownload:true,name:meta.name,mimeType:'application/json',bytes:new TextEncoder().encode(JSON.stringify(env))};}
 if(method!=='POST')fail('Backup operation not found.',404);
 exact(input,id==='import'?['requestId','name','data']:id==='restore'?['requestId','confirm']:['requestId']);
 const receiptKey='backup-receipt:'+input.requestId,identity=await hash(canonical({path,input}));const replay=await atomic(db,[receiptKey],v=>v[receiptKey]);if(replay){if(replay.identity!==identity)fail('This backup request identifier was used for a different action.',409);return clone(replay.result);}
 if(!id||id==='import'){
  const data=id==='import'?await validateBackup(input.data):await atomic(db,['data'],v=>v.data);const env=await envelope(data),backupId=crypto.randomUUID(),name=id==='import'?safeName(input.name):undefined;
  return atomic(db,[receiptKey],(v,store)=>{if(v[receiptKey]){if(v[receiptKey].identity!==identity)fail('Backup request changed.',409);return v[receiptKey].result;}const result=saveBackup(store,backupId,env,name);store.put({identity,result},receiptKey);return result;},true);
 }
 if(uuid(id)&&sub==='restore-preview'){
  const saved=await atomic(db,['backup:'+id,'data','generation'],v=>v);if(!saved['backup:'+id])fail('Backup not found.',404);const candidate=await validateBackup(saved['backup:'+id]),baselineChecksum=await hash(canonical(saved.data)),candidateChecksum=await hash(canonical(candidate)),previewId=crypto.randomUUID(),result={previewId,counts:counts(candidate),ready:true};
  return atomic(db,[receiptKey],(v,store)=>{if(v[receiptKey]){if(v[receiptKey].identity!==identity)fail('Backup request changed.',409);return v[receiptKey].result;}store.put({candidate,baselineChecksum,candidateChecksum,generation:saved.generation??0,createdAt:new Date().toISOString()},'backup-preview:'+previewId);store.put({identity,result},receiptKey);return result;},true);
 }
 if(id==='restore'&&uuid(sub)&&tail==='activate'){
  if(input.confirm!==true)fail('Confirm replacement after reviewing the restore preview.');const previewKey='backup-preview:'+sub,snapshot=await atomic(db,[previewKey,'data','generation'],v=>v),preview=snapshot[previewKey];if(!preview)fail('Restore preview not found. Prepare it again.',404);
  const baseline=canonical(snapshot.data);if((snapshot.generation??0)!==preview.generation||await hash(baseline)!==preview.baselineChecksum)fail('The current workspace changed after this preview. Create a new restore preview.',409,{code:'RESTORE_STALE'});if(await hash(canonical(preview.candidate))!==preview.candidateChecksum)fail('Restore candidate integrity check failed.',422);const rollback=await envelope(snapshot.data),rollbackId=crypto.randomUUID();
  return atomic(db,['data','generation',receiptKey],(v,store)=>{if(v[receiptKey]){if(v[receiptKey].identity!==identity)fail('Backup request changed.',409);return v[receiptKey].result;}if((v.generation??0)!==preview.generation||canonical(v.data)!==baseline)fail('The current workspace changed. Prepare a new restore preview.',409,{code:'RESTORE_STALE'});saveBackup(store,rollbackId,rollback,'Before-restore-'+rollback.createdAt.replace(/[:.]/g,'-')+'.json');store.put(clone(preview.candidate),'data');store.put((v.generation??0)+1,'generation');const result={restored:true,reloadRequired:true,rollbackBackupId:rollbackId};store.put({identity,result},receiptKey);return result;},true);
 }
 fail('Backup operation not found.',404);
}
