import {seed} from './seed.mjs';
import {normalise,dispatch} from './device-model.mjs';
import './device-extensions.mjs';
import {validateDeviceFile} from './device-files.mjs';
const DATABASE='tadsa-device-workspace',STORE='workspace';
export function openDeviceDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE);};request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('Close other TADSA tabs to finish updating device storage.'));});}
let db;
function transact(callback,write=false){return new Promise((resolve,reject)=>{const transaction=db.transaction(STORE,write?'readwrite':'readonly'),store=transaction.objectStore(STORE),request=store.get('data');let result,error;request.onsuccess=()=>{try{let data=request.result;if(!data){const legacy=localStorage.getItem('tadsa-web-v1');data=legacy?JSON.parse(legacy):seed();}data=normalise(data);result=callback(data);if(write)store.put(data,'data');}catch(e){error=e;transaction.abort();}};transaction.oncomplete=()=>resolve(result);transaction.onabort=()=>reject(error??transaction.error??Error('Device storage could not save. Changes were not committed.'));transaction.onerror=()=>{};});}
export async function installDeviceApi(){db=await openDeviceDatabase();await transact(()=>null,true);const original=globalThis.fetch.bind(globalThis);globalThis.fetch=async(input,options={})=>{const url=new URL(typeof input==='string'||input instanceof URL?input:input.url,location.href);if(url.origin!==location.origin||!url.pathname.startsWith('/api/'))return original(input,options);try{const method=(options.method??input.method??'GET').toUpperCase();let body={};if(options.body)body=JSON.parse(options.body);else if(input instanceof Request&&method!=='GET')body=await input.json();if(method==='POST'&&/^\/api\/projects\/[^/]+\/attachments$/.test(url.pathname))await validateDeviceFile(body);if(options.signal?.aborted)throw options.signal.reason;const result=await transact(data=>dispatch(data,url.pathname.slice(5),method,body,url.searchParams),method!=='GET');if(result?.deviceDownload)return new Response(result.bytes,{headers:{'Content-Type':result.mimeType,'Content-Disposition':`attachment; filename="${result.name.replace(/["\r\n]/g,'_')}"`}});return Response.json(result,{headers:{'Cache-Control':'no-store'}});}catch(e){return Response.json({error:e.status?e.message:'Device storage is unavailable or full. Your changes were not saved.',...(e.code?{code:e.code}:{}),...(e.candidates?{candidates:e.candidates}:{})},{status:e.status??503});}};return {exportData:()=>transact(d=>structuredClone(d)),reset:()=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(normalise(seed()),'data');tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);})};}
