import {fail} from './device-model.mjs';
const invalid=()=>fail('The file is unsupported, damaged or contains unsupported active Word content.');
const crc32=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
async function inflate(bytes,limit){const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),chunks=[];let size=0;try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();invalid();}chunks.push(value);}}catch{invalid();}const result=new Uint8Array(size);let at=0;for(const chunk of chunks){result.set(chunk,at);at+=chunk.length;}return result;}
export async function validateDeviceFile(input){
 if(typeof input.name!=='string'||!input.name.trim()||input.name.length>180||/[\\/<>:"|?*\u0000-\u001f\u007f]/.test(input.name)||/[. ]$/.test(input.name)||input.name.startsWith('.'))invalid();
 const types={'image/png':['png'],'image/jpeg':['jpg','jpeg'],'application/pdf':['pdf'],'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['docx']};if(!types[input.mime]?.includes(input.name.split('.').pop().toLowerCase()))invalid();
 if(typeof input.dataBase64!=='string'||input.dataBase64.length>13981016||!input.dataBase64.length||input.dataBase64.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(input.dataBase64))invalid();let raw;try{raw=atob(input.dataBase64);}catch{invalid();}if(!raw.length||raw.length>10485760||btoa(raw)!==input.dataBase64)invalid();const data=Uint8Array.from(raw,c=>c.charCodeAt(0));
 if(input.mime==='image/png'&&(raw.length<45||!raw.startsWith('\x89PNG\r\n\x1a\n')||raw.slice(12,16)!=='IHDR'||raw.slice(-8,-4)!=='IEND'))invalid();
 if(input.mime==='image/jpeg'&&(raw.length<10||!raw.startsWith('\xff\xd8')||!raw.endsWith('\xff\xd9')||!raw.includes('\xff\xda')))invalid();
 if(input.mime==='application/pdf'&&(!raw.startsWith('%PDF-')||!raw.slice(-1024).includes('%%EOF')))invalid();
 if(input.mime.endsWith('wordprocessingml.document')){
  const view=new DataView(data.buffer),u16=i=>view.getUint16(i,true),u32=i=>view.getUint32(i,true),decode=(a,b)=>new TextDecoder().decode(data.subarray(a,b));let end=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--)if(u32(i)===0x06054b50){end=i;break;}
  if(end<0||u16(end+4)||u16(end+6)||end+22+u16(end+20)!==data.length)invalid();const count=u16(end+10),centralSize=u32(end+12),centralStart=u32(end+16);if(!count||count>500||u16(end+8)!==count||centralStart+centralSize!==end)invalid();let at=centralStart,total=0;const names=new Set();
  for(let n=0;n<count;n++){
   if(at+46>end||u32(at)!==0x02014b50)invalid();const flags=u16(at+8),method=u16(at+10),crc=u32(at+16),compressed=u32(at+20),expanded=u32(at+24),nameLength=u16(at+28),extra=u16(at+30),comment=u16(at+32),local=u32(at+42);if(at+46+nameLength+extra+comment>end)invalid();const name=decode(at+46,at+46+nameLength);
   if((flags&1)||![0,8].includes(method)||!name||name.includes('\\')||name.startsWith('/')||name.split('/').includes('..')||names.has(name)||/[\u0000-\u001f]/.test(name)||/vba|\.bin$|embeddings\//i.test(name))invalid();names.add(name);total+=expanded;if(total>52428800||expanded>10485760||local+30>centralStart||u32(local)!==0x04034b50)invalid();const localName=u16(local+26),localExtra=u16(local+28),start=local+30+localName+localExtra;if(start+compressed>centralStart||u16(local+8)!==method||u16(local+6)!==flags||decode(local+30,local+30+localName)!==name)invalid();const bytes=data.subarray(start,start+compressed),content=method===0?bytes:await inflate(bytes,Math.max(1,expanded));if(content.length!==expanded||crc32(content)!==crc)invalid();let xml='';if(name.endsWith('.xml')||name.endsWith('.rels')){try{xml=new TextDecoder('utf-8',{fatal:true}).decode(content);}catch{invalid();}if(xml.includes('\u0000')||(/<\?xml[^>]*encoding\s*=\s*[\"']([^\"']+)[\"']/i.test(xml)&&!/^utf-8$|^us-ascii$/i.test(xml.match(/<\?xml[^>]*encoding\s*=\s*[\"']([^\"']+)[\"']/i)[1]))||/<!DOCTYPE|<!ENTITY|DDEAUTO|DDE\s|INCLUDETEXT|INCLUDEPICTURE/i.test(xml))invalid();}if((name.endsWith('.rels')||name==='[Content_Types].xml')&&/&#/i.test(new TextDecoder().decode(content)))invalid();if((name.endsWith('.rels')||name==='[Content_Types].xml')&&(/TargetMode\s*=\s*["']External["']/i.test(new TextDecoder().decode(content))||/macroEnabled|vbaProject|<!DOCTYPE|<!ENTITY/i.test(new TextDecoder().decode(content))))invalid();at+=46+nameLength+extra+comment;
  }
  if(at!==end||!names.has('[Content_Types].xml')||!names.has('word/document.xml'))invalid();
 }
 return {sha256:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),b=>b.toString(16).padStart(2,'0')).join('')};
}
