// Shared domain rules. Caller owns authentication, reviewer lookup, persistence,
// optimistic version checks, holds and transactional audit.
const fail=(message,status=422)=>{const e=new Error(message);e.status=status;throw e;};
const exact=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))fail('Supply exactly the fields for this lifecycle action.');};
const text=(v,max=1000,required=true)=>{if(typeof v!=='string'||v.trim().length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v)||(required&&!v.trim()))fail('Record the required description or evidence reference.');return v.trim();};
const day=v=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1900-01-01'||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('Enter a valid recorded date.');return v;};
const optionalExact=(v,required,optional)=>{if(!v||typeof v!=='object'||Array.isArray(v)||required.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>!required.includes(k)&&!optional.includes(k)))fail('Supply exactly the fields for this lifecycle action.');};
const bikeCount=v=>{if(!Number.isSafeInteger(v)||v<1||v>10000)fail('Record a whole bike count between 1 and 10,000.');return v;};
const currentQuote=s=>s.quotes.at(-1);
const readyAssessment=s=>s.assessmentDecision&&(!s.assessmentDecision.required||s.assessment);
export function createLifecycle(){return {schema:1,stage:'enquiry',revisionRequested:null,costReturns:[],cancellation:null,assessmentDecision:null,assessment:null,quotes:[],peerReview:null,acceptance:null,financeClearance:null,work:null,signoff:null,financeFinalisation:null,closed:null,history:[]};}
export function lifecycleGate(s){const reasons=[];const q=s&&currentQuote(s);if(!s)reasons.push('This historical project has not adopted the lifecycle.');else{if(s.cancellation)reasons.push('This project is cancelled pending financial finalisation.');if(s.revisionRequested)reasons.push('Prepare the requested new quote revision.');if(!readyAssessment(s))reasons.push('Record the assessment decision and any required assessment.');if(!q)reasons.push('Prepare a quote.');if(!s.peerReview?.approved||s.peerReview.quoteVersion!==q?.version)reasons.push('Record technical peer review of the current quote.');if(s.acceptance?.quoteVersion!==q?.version||!s.acceptance)reasons.push('Record client acceptance of the current quote.');if(s.financeClearance?.quoteVersion!==q?.version||!s.financeClearance)reasons.push('Record external finance payment or exemption clearance for the current quote.');if(s.closed)reasons.push('The project is closed.');}return {allowed:reasons.length===0,reasons};}
const returnStages=['enquiry','assessment','quote','peer_review','client_acceptance','finance_clearance','work','customer_signoff','finance_finalisation','ready_to_close'];
export function lifecycleReturnTargets(s){if(!s||s.closed||s.cancellation)return [];return returnStages.slice(0,Math.max(0,returnStages.indexOf(stage(s)))).filter(target=>target!=='assessment'||s.assessmentDecision?.required);}
function stage(s){if(s.closed)return 'closed';if(s.cancellation)return s.financeFinalisation?'ready_to_close':'finance_finalisation';if(!s.assessmentDecision)return 'enquiry';if(s.assessmentDecision.required&&!s.assessment)return 'assessment';if(s.revisionRequested)return 'quote';if(s.financeFinalisation)return 'ready_to_close';if(s.signoff)return 'finance_finalisation';if(s.work?.status==='complete')return 'customer_signoff';if(lifecycleGate(s).allowed)return 'work';if(s.acceptance)return 'finance_clearance';if(s.peerReview?.approved)return 'client_acceptance';if(currentQuote(s))return 'peer_review';if(!s.assessmentDecision)return 'enquiry';if(s.assessmentDecision.required&&!s.assessment)return 'assessment';return 'quote';}
function clearFollowingQuote(s){s.peerReview=null;s.acceptance=null;s.financeClearance=null;s.signoff=null;s.financeFinalisation=null;s.closed=null;if(s.work)s.work={...s.work,status:'paused'};}
export function applyLifecycle(previous,action,data,context){
 const actor=context?.actor??{id:null,displayName:'Synthetic demonstration operator',role:'administrator'},at=context?.at;
 if(typeof at!=='string'||Number.isNaN(Date.parse(at)))fail('A trusted event time is required.');
 const occurredOn=v=>{const date=day(v),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Adelaide'}).format(new Date(at));if(date>today)fail('An actual event date cannot be in the future.');return date;};
 const programmeEvidence=Object.hasOwn(context,'programme')?{programme:context.programme}:{};if(Object.hasOwn(context,'programme')&&!['','TAD','FW'].includes(context.programme))fail('Invalid programme evidence.');
 if(action==='begin'){exact(data,[]);if(previous)fail('This project already uses the lifecycle.');if(context.projectStatus==='closed')fail('Reopen this historical project before adopting its lifecycle.');const s=createLifecycle();s.history.push({action,data:{},actor,at,...programmeEvidence});return s;}
 if(!previous)fail('Start the project lifecycle first.');const s=structuredClone(previous);
 if(s.cancellation&&!['costReturn','financeFinalise','close','reopen'].includes(action))fail('Cancellation requires finance finalisation and closure before reopening.');
 if(s.closed&&action!=='reopen')fail('Reopen the project before changing its lifecycle.');
 let value;
 switch(action){
  case 'assessmentDecision':exact(data,['required','reason']);if(typeof data.required!=='boolean')fail('Choose whether an assessment is required.');if(s.quotes.length&&stage(s)!=='enquiry')fail('Return to the assessment decision before changing it.');value={required:data.required,reason:text(data.reason)};s.assessmentDecision=value;s.assessment=null;break;
  case 'assessmentComplete':exact(data,['notes']);if(!s.assessmentDecision?.required)fail('An assessment must be selected first.');if(s.quotes.length&&stage(s)!=='assessment')fail('Return to assessment before changing it.');value={notes:text(data.notes)};s.assessment=value;break;
  case 'quote':{
   exact(data,['lines','notes']);if(!readyAssessment(s))fail('Complete the assessment decision first.');if(s.work&&s.work.status!=='paused')fail('Request a revision and pause work before changing the quote.');if(s.acceptance||s.financeClearance)fail('Request a revision before replacing an accepted quote.');if(!Array.isArray(data.lines)||!data.lines.length||data.lines.length>20)fail('Record between one and twenty quote lines.');
   const lines=data.lines.map(l=>{exact(l,['type','description','quantityMilli','unitPriceCents']);if(!['labour','materials'].includes(l.type)||!Number.isSafeInteger(l.quantityMilli)||l.quantityMilli<1||l.quantityMilli>1000000||!Number.isSafeInteger(l.unitPriceCents)||l.unitPriceCents<0||l.unitPriceCents>100000000)fail('Use valid quote types, quantities and integer-cent prices.');const amountCents=Math.round(l.quantityMilli*l.unitPriceCents/1000);return {type:l.type,description:text(l.description,300),quantityMilli:l.quantityMilli,unitPriceCents:l.unitPriceCents,amountCents};});const totalCents=lines.reduce((n,l)=>n+l.amountCents,0);if(totalCents>1000000000)fail('Quote total is too large.');value={version:(currentQuote(s)?.version??0)+1,lines,totalCents,notes:text(data.notes,2000,false),at,actor};clearFollowingQuote(s);s.revisionRequested=null;s.quotes.push(value);break;
  }
  case 'peerReview':exact(data,['quoteVersion','reviewerId','approved','notes']);if(s.revisionRequested||!currentQuote(s)||data.quoteVersion!==currentQuote(s).version)fail('Review the current quote version.');if(s.acceptance||s.work&&s.work.status!=='paused')fail('Request a revision before changing an accepted review.');if(typeof data.approved!=='boolean')fail('Record the review decision.');value={quoteVersion:data.quoteVersion,reviewerId:text(data.reviewerId,100),approved:data.approved,notes:text(data.notes),at,actor};s.peerReview=value;if(!data.approved&&!context.legacyPeerReview){value.requiresRevision=true;s.revisionRequested={reason:value.notes,at,actor};}break;
  case 'issueQuote':exact(data,['quoteVersion','sentOn']);if(s.revisionRequested||!s.peerReview?.approved||data.quoteVersion!==currentQuote(s)?.version||s.peerReview.quoteVersion!==data.quoteVersion)fail('The current quote needs technical peer review first.');if(s.history.some(e=>e.action==='issueQuote'&&e.data.quoteVersion===data.quoteVersion))fail('This quote revision is already recorded as sent.');value={quoteVersion:data.quoteVersion,sentOn:occurredOn(data.sentOn),at,actor};break;
  case 'acceptQuote':exact(data,['quoteVersion','acceptedBy','reference','date']);if(!s.peerReview?.approved||data.quoteVersion!==currentQuote(s)?.version||s.peerReview.quoteVersion!==data.quoteVersion)fail('The current quote needs technical peer review first.');if(s.acceptance)fail('Client acceptance is already recorded; request a revision to change it.');value={quoteVersion:data.quoteVersion,acceptedBy:text(data.acceptedBy,120),reference:text(data.reference,300),date:day(data.date),at,actor};s.acceptance=value;break;
  case 'returnTo':{
   exact(data,['target','reason']);if(!lifecycleReturnTargets(s).includes(data.target))fail('Choose an earlier completed workflow step.');value={target:data.target,reason:text(data.reason)};const index=returnStages.indexOf(data.target);
   if(index<=3)clearFollowingQuote(s);
   if(index<=2)s.revisionRequested={reason:value.reason,at,actor};
   if(index<=1)s.assessment=null;
   if(index===0)s.assessmentDecision=null;
   if(index<=4)s.acceptance=null;
   if(index<=5)s.financeClearance=null;
   if(index<=6&&s.work)s.work={...s.work,status:'paused'};
   if(index<=7)s.signoff=null;
   s.financeFinalisation=null;s.closed=null;break;
  }
  case 'revise':exact(data,['reason']);if(!currentQuote(s))fail('There is no quote to revise.');value={reason:text(data.reason)};clearFollowingQuote(s);s.revisionRequested={...value,at,actor};break;
  case 'financeClearance':exact(data,['quoteVersion','status','reference','notes','confirmedOn']);if(actor.role!=='administrator')fail('An administrator must record finance confirmation.',403);if(!s.acceptance||data.quoteVersion!==currentQuote(s)?.version||s.acceptance.quoteVersion!==data.quoteVersion)fail('Record client acceptance before finance clearance.');if(!['paid','exempt'].includes(data.status))fail('Choose recorded payment or authorised exemption.');if(s.work&&s.work.status!=='paused')fail('Pause work through a revision before changing finance clearance.');value={quoteVersion:data.quoteVersion,status:data.status,reference:text(data.reference,300),notes:text(data.notes,2000,data.status==='exempt'),confirmedOn:day(data.confirmedOn),verification:'operator-recorded-external',at,actor};s.financeClearance=value;break;
  case 'work':optionalExact(data,['status','notes'],['deliveredOn','deliveredQuantity']);if(!['in_progress','complete'].includes(data.status))fail('Choose work in progress or completed.');if(!lifecycleGate(s).allowed)fail(lifecycleGate(s).reasons.join(' '));if(context.onHold||context.clientStopped)fail('Resolve the project hold and client stop before work continues.');if(s.signoff)fail('Customer sign-off is already recorded.');value={status:data.status,notes:text(data.notes),at,actor};if(Object.hasOwn(data,'deliveredOn')||Object.hasOwn(data,'deliveredQuantity')){if(data.status!=='complete')fail('Record final delivery with completed work.');if(context.programme!=='FW')fail('Bike delivery is only recorded for Freedom Wheels projects.');value.deliveredOn=occurredOn(data.deliveredOn);value.deliveredQuantity=bikeCount(data.deliveredQuantity);}s.work=value;break;
  case 'signoff':exact(data,['acceptedBy','reference','signedOn','notes']);if(s.work?.status!=='complete')fail('Complete work before recording customer sign-off.');if(s.signoff)fail('Customer sign-off is already recorded.');value={acceptedBy:text(data.acceptedBy,120),reference:text(data.reference,300),signedOn:day(data.signedOn),notes:text(data.notes,2000,false),at,actor};s.signoff=value;break;
  case 'costReturn':{
   exact(data,['lines','notes']);if(s.financeFinalisation)fail('Finance is already finalised; reopen before changing actual costs.');if(!s.work&&!s.cancellation)fail('Start work or record cancellation before returning actual costs.');if(!Array.isArray(data.lines)||data.lines.length>20)fail('Record at most twenty actual-cost lines.');const lines=data.lines.map(l=>{exact(l,['type','description','quantityMilli','unitPriceCents']);if(!['labour','materials'].includes(l.type)||!Number.isSafeInteger(l.quantityMilli)||l.quantityMilli<1||l.quantityMilli>1000000||!Number.isSafeInteger(l.unitPriceCents)||l.unitPriceCents<0||l.unitPriceCents>100000000)fail('Use valid quantities and integer-cent prices.');return {...l,description:text(l.description,300),amountCents:Math.round(l.quantityMilli*l.unitPriceCents/1000)};});const totalCents=lines.reduce((n,l)=>n+l.amountCents,0);if(totalCents>1000000000)fail('Actual-cost total is too large.');s.costReturns??=[];value={version:s.costReturns.length+1,lines,totalCents,notes:text(data.notes,2000,!lines.length),at,actor};s.costReturns.push(value);break;
  }
  case 'cancel':optionalExact(data,['reason'],['cancelledQuantity']);if(s.cancellation)fail('Cancellation is already recorded.');value={reason:text(data.reason),at,actor};if(Object.hasOwn(data,'cancelledQuantity')){if(context.programme!=='FW')fail('Bike cancellation is only recorded for Freedom Wheels projects.');value.cancelledQuantity=bikeCount(data.cancelledQuantity);}s.cancellation=value;s.financeFinalisation=null;s.work={status:'stopped',notes:value.reason,at,actor};break;
  case 'financeFinalise':exact(data,['reference','confirmedOn','notes']);if(actor.role!=='administrator')fail('An administrator must record finance finalisation.',403);if(!s.signoff&&!s.cancellation)fail('Record customer sign-off before finance finalisation.');if(!s.costReturns?.length)fail('Record the actual cost return, including a no-cost explanation when appropriate.');if(s.financeFinalisation)fail('Finance finalisation is already recorded.');value={reference:text(data.reference,300),confirmedOn:day(data.confirmedOn),notes:text(data.notes,2000,false),costReturnVersion:s.costReturns.at(-1).version,verification:'operator-recorded-external',at,actor};s.financeFinalisation=value;break;
  case 'close':exact(data,['reason']);if(!s.financeFinalisation||(!s.cancellation&&(!s.signoff||s.work?.status!=='complete')))fail('Finish work, customer sign-off and finance finalisation before closing.');if(context.onHold||context.clientStopped){if(!s.cancellation)fail('Resolve the hold before closing the project.');}value={reason:text(data.reason),at,actor};s.closed=value;break;
  case 'reopen':exact(data,['reason']);if(!s.closed)fail('This project is not closed.');value={reason:text(data.reason)};s.closed=null;s.signoff=null;s.financeFinalisation=null;if(s.cancellation){s.cancellation=null;clearFollowingQuote(s);s.work=null;if(s.quotes.length)s.revisionRequested={...value,at,actor};}else s.work={status:'in_progress',notes:value.reason,at,actor};break;
  default:fail('Choose a supported lifecycle action.');
 }
 s.stage=stage(s);s.history.push({action,data:value,at,actor,...programmeEvidence});return s;
}
