import {node,accountRequest,passwordChange} from './accounts.js';
export let sessionEnded=false;
export async function requireLocalSession(container,refresh,isCurrent=()=>true,hasDrafts=()=>false){
 const status=await accountRequest('auth/status',undefined,'GET');if(!isCurrent())return false;
 document.querySelector('#local-session')?.remove();document.querySelector('#local-signout')?.remove();
 if(!status.configured){if(!status.setupRequired)return true;
 const form=node('form',undefined,'panel workflow-panel form-grid');form.append(node('h1','Set up the first administrator'),node('p','Local IT setup: create the first named account administrator. This creates a linked Administrator person profile. Keep the password private.'));const fields={};for(const [key,label]of [['username','Username'],['displayName','Display name'],['password','Password']]){const wrap=node('label',label),input=node('input');input.required=true;input.type=key==='password'?'password':'text';input.maxLength=key==='password'?128:key==='username'?60:120;if(key==='password'){input.minLength=12;input.autocomplete='new-password';}wrap.append(input);form.append(wrap);fields[key]=input;}const message=node('p');message.setAttribute('role','alert');const submit=node('button','Create first administrator','primary');form.append(message,submit);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await accountRequest('auth/bootstrap',Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])));fields.password.value='';await refresh();}catch(e){message.textContent=e.message;submit.disabled=false;}};container.replaceChildren(form);fields.username.focus();return false;}

 const demo=status.mode==='device-demo';
 if(status.authenticated){
  const bar=node('div',undefined,'session-controls');bar.id='local-session';const name=node('a',(demo?'Demo: ':'')+(status.user.displayName||status.user.username));name.href='#accounts';bar.append(name);
  const signout=node('button',demo?'Switch demo user':'Sign out','secondary');signout.type='button';signout.id='local-signout';signout.onclick=async()=>{if(hasDrafts()&&!confirm('Sign out and discard unsaved changes?'))return;signout.disabled=true;try{await accountRequest('auth/logout',{});sessionEnded=true;container.replaceChildren();location.reload();}catch{signout.disabled=false;signout.textContent='Retry sign out';}};bar.append(signout);document.querySelector('.topbar').append(bar);
  if(status.user.mustChangePassword&&!demo){container.replaceChildren(node('h1','Set your own password'));passwordChange(container,()=>{sessionEnded=true;location.reload();});return false;}return true;
 }
 const form=node('form',undefined,'panel workflow-panel form-grid');form.append(node('h1',demo?'Explore the TADSA demonstration':'Sign in to TADSA'));
 const message=node('p');message.setAttribute('role','alert');
 if(demo){form.append(node('p','Fictional data stays in this browser. Demo profiles are not secure accounts: anyone can select them. Do not enter real personal information or passwords.'));const button=node('button','Enter as demo administrator','primary');button.type='button';const enter=async accountId=>{button.disabled=true;try{await accountRequest('auth/demo-entry',accountId?{accountId}:{});await refresh();}catch(e){message.textContent=e.message;button.disabled=false;}};button.onclick=()=>enter();form.append(button);const select=node('select');select.setAttribute('aria-label','Demo profile');select.append(new Option('Choose another demo profile',''));for(const a of status.demoProfiles||[])select.append(new Option(a.displayName+' · '+a.role,a.id));const switcher=node('button','Enter selected demo profile','secondary');switcher.type='button';switcher.onclick=()=>{if(select.value)enter(select.value);else message.textContent='Choose a demo profile.';};form.append(select,switcher,message);container.replaceChildren(form);button.focus();return false;}
 const fields={};for(const [name,label,type]of [['username','Username','text'],['password','Password','password']]){const wrap=node('label',label),input=node('input');input.type=type;input.required=true;input.autocomplete=name==='username'?'username':'current-password';wrap.append(input);form.append(wrap);fields[name]=input;}
 const button=node('button','Sign in','primary');form.append(message,button,node('p','For a local password reset, contact your nominated account administrator or IT provider.'));
 form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{await accountRequest('auth/login',{username:fields.username.value,password:fields.password.value});fields.password.value='';await refresh();}catch(e){message.textContent=e.message;button.disabled=false;}};container.replaceChildren(form);fields.username.focus();return false;
}
