import {advanceLifecycleDraftAfterNote} from './project-care.js';
let host;
const drafts=new Map();
export const configureOperations=h=>{host=h;};
export const operationsHaveDrafts=()=>drafts.size>0;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const link=(text,hash)=>{const a=node('a',text,'button secondary');a.href='#'+hash;return a;};
const button=(text,fn)=>{const b=node('button',text,'secondary');b.type='button';b.onclick=fn;return b;};
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const data=await r.json();if(!r.ok){const e=Error(data.error);e.status=r.status;throw e;}return data;}
const notice=(text,error=false)=>{const n=node('p',text,error?'message error':'message');n.setAttribute('role',error?'alert':'status');return n;};
function input(parent,label,d,key,type='text'){const l=node('label',null,'workflow-field');l.append(node('span',label,'field-label'));const n=node(type==='textarea'?'textarea':'input');if(type!=='textarea')n.type=type;n.setAttribute('aria-label',label);n.value=d[key]??'';if(type==='number'){n.min='0';n.step='1';}if(type==='textarea'){n.rows=3;n.maxLength=2000;}else if(type==='text')n.maxLength=200;n.oninput=()=>{d[key]=n.value;};l.append(n);parent.append(l);return n;}
function select(parent,label,d,key,values){const l=node('label',null,'workflow-field');l.append(node('span',label,'field-label'));const n=node('select');n.setAttribute('aria-label',label);for(const[v,t]of values){const o=node('option',t);o.value=v;n.append(o);}n.value=d[key]??'';n.onchange=()=>d[key]=n.value;l.append(n);parent.append(l);return n;}
function check(parent,label,d,key){const l=node('label',null,'checkbox'),n=node('input');n.type='checkbox';n.checked=d[key];n.onchange=()=>d[key]=n.checked;l.append(n,node('span',label));parent.append(l);}
const money=c=>(c/100).toFixed(2);
function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))throw Error('Enter a positive dollar amount with at most two decimal places.');return Math.round(Number(value)*100);}
const scalarKeys=['actualMinutes','remainingMinutes','assessmentComplete','workApproved','approvedBy','approvedOn','fundingExceptionReason','onHold','clientStopped','resumeClientConsent','reviewRequired'];
async function send(form,d,key,path,method,payload,feedback,submit){
  if(host.isSaving())return;const workspace=form.closest('main'),wasInert=workspace?.inert??false;let refreshed=false;
  host.setSaving(true);d.pending??=payload;if(workspace){workspace.inert=true;workspace.setAttribute('aria-busy','true');}
  form.querySelectorAll('input,select,textarea,button').forEach(n=>n.disabled=true);feedback.replaceChildren(notice('Saving…'));
  try{const result=await api(path,method,d.pending);if(/^projects\/[^/]+\/notes$/.test(path))advanceLifecycleDraftAfterNote(path.split('/')[1],d.baseVersion,result.version);window.dispatchEvent(new Event('tadsa-saved'));drafts.delete(key);host.setSaving(false);await host.refresh();refreshed=true;}
  catch(e){if(e.status){d.pending=null;d.requestId=crypto.randomUUID();}feedback.replaceChildren(notice(e.status?e.message:'Save result not confirmed. Retry the same save safely.',true));if(e.status===401)feedback.append(button('Sign in and keep draft',()=>host.refresh()));if(e.status===409&&method==='PUT')feedback.append(button('Compare latest case',()=>host.refresh()));}
  finally{host.setSaving(false);if(workspace){workspace.inert=wasInert;workspace.removeAttribute('aria-busy');}form.querySelectorAll('input,select,textarea,button').forEach(n=>n.disabled=Boolean(d.pending)&&n!==submit);submit.disabled=false;submit.textContent=d.pending?'Retry save safely':submit.dataset.label;if(!wasInert){if(refreshed)workspace?.focus({preventScroll:true});else submit.focus({preventScroll:true});}}
}
export async function renderOperations(view,route,id,options={}){
  if(route==='review-queue'){view.append(node('h1','Needs attention'),node('p','Shared queue: any administrator or coordinator can pick up an item.','subtitle'));const q=await api('review-queue');if(!q.items.length)view.append(notice('No flagged cases.'));for(const p of q.items){const box=node('section',null,'panel');box.append(link(p.title||p.reference||p.projectId,'operations/'+(p.projectId||p.id)),node('p',p.reason||'Review the case, funding or hold details.'));view.append(box);}return true;}
  if(!['operations','documents'].includes(route))return false;
  const [p,ops,people,orgs,approvers,business,clients]=await Promise.all([api('projects/'+id),api(`projects/${id}/operations`),api('people'),api('organisations'),api('approvers'),api('business-settings'),api('clients')]);
  const lifecycle=await api(`projects/${id}/lifecycle`);
  const requestedFocus=options.focus??location.hash.split('/')[2],focus=route==='operations'&&['invoices','hours','holds'].includes(requestedFocus)?requestedFocus:'';
  ops.invoices=ops.invoices.map(i=>({...i,...i.snapshot}));
  if(!options.embedded)view.append(link('← Back to project','project/'+id),node('h1',route==='documents'?'Project documents':({invoices:'Prepare draft invoice',hours:'Record project hours',holds:'Hold or resume work'})[focus]||'Case workspace'),node('p',p.title,'subtitle'));
  if(route==='documents'){renderDocuments(view,p,ops,lifecycle);return true;}
  const sections=node('nav',null,'actions');sections.setAttribute('aria-label','Case workspace sections');for(const[label,heading]of [['Hours & holds','Hours, funding and holds'],['Case notes','Case notes'],...(lifecycle.managed||p.kind!=='Assessment'?[['Draft invoices','Draft invoices']]:[])])sections.append(button(label,()=>{const target=[...view.querySelectorAll('h2')].find(h=>h.textContent===heading);if(target){target.tabIndex=-1;target.scrollIntoView({block:'start'});target.focus({preventScroll:true});}}));view.append(sections);
 const key='case/'+id+(focus?'/'+focus:''),d=drafts.get(key)??{...ops,requestId:crypto.randomUUID(),fundingContributors:ops.fundingContributors.map(c=>({...c,amount:money(c.amountCents)}))};
  const box=node('section',null,'panel workflow-panel'),form=node('form',null,'form-grid');form.classList.add('operations-form');box.append(node('h2','Hours, funding and holds'),form);view.append(box);
  form.addEventListener('input',()=>drafts.set(key,d));form.addEventListener('change',()=>drafts.set(key,d));
  input(form,'Actual hours worked (running total)',d,'actualHours','number').value=d.actualHours??Number(d.actualMinutes)/60;
  input(form,'Estimated hours remaining',d,'remainingHours','number').value=d.remainingHours??Number(d.remainingMinutes)/60;
  for(const n of form.querySelectorAll('input[type=number]'))n.step='0.25';
  const funding=node('fieldset');funding.className='funding-fields';funding.append(node('legend','Payer contributions'),node('p','Record a dollar contribution for each payer. This does not record payment received.','field-help'));const rows=node('div');funding.append(rows);
  const payerOptions=[['client:'+p.clientId,p.clientName+' (client)'],...[...people.items].sort((a,b)=>a.name.localeCompare(b.name,'en-AU')).map(v=>['person:'+v.id,v.name]),...[...orgs.items].sort((a,b)=>a.name.localeCompare(b.name,'en-AU')).map(v=>['organisation:'+v.id,v.name])];
  function draw(){rows.replaceChildren();d.fundingContributors.forEach((c,i)=>{const row=node('div',null,'panel');const state={target:c.type+':'+c.id};const picker=select(row,'Payer '+(i+1),state,'target',payerOptions);picker.onchange=()=>{[c.type,c.id]=picker.value.split(':');drafts.set(key,d);};input(row,'Contribution '+(i+1)+' ($)',c,'amount');row.append(button('Remove payer '+(i+1),()=>{d.fundingContributors.splice(i,1);drafts.set(key,d);draw();}));rows.append(row);});}
  funding.append(button('Add payer',()=>{d.fundingContributors.push({type:'client',id:p.clientId,amount:''});drafts.set(key,d);draw();}));draw();form.append(funding);
  const approvals=node('fieldset');approvals.hidden=Boolean(lifecycle.managed);approvals.append(node('legend','Assessment and work approval'));check(approvals,'Assessment completed',d,'assessmentComplete');check(approvals,'Work approved by administrator/coordinator',d,'workApproved');const approverOptions=[['','Choose an administrator'],...approvers.items.map(a=>[a.id,a.name])];if(d.approvedBy&&!approvers.items.some(a=>a.id===d.approvedBy))approverOptions.push([d.approvedBy,'Previous entry — choose an administrator']);select(approvals,'Approver',d,'approvedBy',approverOptions);input(approvals,'Approval date',d,'approvedOn','date');input(approvals,'Funding context (does not bypass payment)',d,'fundingExceptionReason','textarea');approvals.append(node('p','Historical work approvals are retained. Adopt the guided workflow on the project to record current assessment, acceptance and Finance clearance.','field-help'));form.append(approvals);
  const state=node('fieldset');state.append(node('legend','Hold and review'));check(state,'Client asked work to stop',d,'clientStopped');check(state,'Work is on hold',d,'onHold');check(state,'Client agreed to resume work',d,'resumeClientConsent');check(state,'Needs administrator review',d,'reviewRequired');if(lifecycle.managed)state.append(node('p','After a client stop, an account administrator must record the client’s agreement to resume. The guided workflow keeps the technical and Finance approvals; no separate legacy approver entry is needed.','field-help'));form.append(state);
  if(lifecycle.managed)state.append(node('p','To resume, tick “Client agreed to resume work”, clear “Client asked work to stop” and “Work is on hold”, then save. Clear “Needs administrator review” only when that review is complete. Recording consent alone keeps the hold in place.','field-help'));
  const feedback=node('div'),actions=node('div',null,'actions'),submit=node('button','Save case details','primary');submit.type='submit';submit.dataset.label='Save case details';actions.append(submit,button('Discard unsaved case changes',()=>{drafts.delete(key);host.refresh();}));form.append(feedback,actions);
  if(d.version!==ops.version&&!d.pending){feedback.append(notice('The project changed since this draft began. Compare the latest saved case below before keeping your draft.',true),node('pre',JSON.stringify(Object.fromEntries([...scalarKeys,'fundingContributors'].map(k=>[k,ops[k]])),null,2),'case-comparison'),button('Use latest version with my draft',()=>{d.version=ops.version;d.requestId=crypto.randomUUID();feedback.replaceChildren(notice('Latest version acknowledged. Review and save your draft.'));}));}
  form.onsubmit=e=>{e.preventDefault();try{drafts.set(key,d);const ownKeys=focus==='holds'?['onHold','clientStopped','resumeClientConsent','reviewRequired']:[];const payload={requestId:d.requestId,version:d.version,...Object.fromEntries(scalarKeys.map(k=>[k,focus&&!ownKeys.includes(k)?ops[k]:d[k]])),actualMinutes:focus&&focus!=='hours'?ops.actualMinutes:Math.round(Number(d.actualHours??ops.actualMinutes/60)*60),remainingMinutes:focus&&focus!=='hours'?ops.remainingMinutes:Math.round(Number(d.remainingHours??ops.remainingMinutes/60)*60),fundingContributors:focus&&focus!=='invoices'?ops.fundingContributors.map(c=>({type:c.type,id:c.id,amountCents:c.amountCents})):d.fundingContributors.map(c=>({type:c.type,id:c.id,amountCents:cents(c.amount)}))};if(payload.clientStopped){payload.onHold=true;payload.reviewRequired=true;}send(form,d,key,`projects/${id}/operations`,'PUT',payload,feedback,submit);}catch(e){feedback.replaceChildren(notice(e.message,true));}};
  if(d.pending){form.querySelectorAll('input,textarea,select,button').forEach(n=>n.disabled=n!==submit);submit.textContent='Retry save safely';}
  if(!focus)renderNotes(view,id,ops);if(!['hours','holds'].includes(focus))renderInvoices(view,id,p,ops,payerOptions,business,clients.items,people.items,lifecycle,()=>{funding.scrollIntoView({block:'start'});(funding.querySelector('input[aria-label^="Contribution"]')||[...funding.querySelectorAll('button')].find(b=>b.textContent==='Add payer'))?.focus({preventScroll:true});});view.append(link('Review and print documents','documents/'+id));
  if(focus){sections.hidden=true;funding.hidden=focus!=='invoices';state.hidden=focus!=='holds';approvals.hidden=true;for(const label of form.querySelectorAll(':scope > label'))label.hidden=focus!=='hours';box.querySelector('h2').textContent=({invoices:'Payer contributions',hours:'Hours worked and remaining',holds:'Hold and client consent'})[focus];submit.textContent=submit.dataset.label=({invoices:'Save payer contributions',hours:'Save hours',holds:'Save hold status'})[focus];if(currentHold(lifecycle))box.prepend(notice(lifecycle.workGate.reasons.filter(r=>/hold|stop/i.test(r)).join(' ')));}
  return true;
}
function currentHold(lifecycle){return lifecycle.workGate?.reasons?.some(r=>/hold|stop/i.test(r));}
export function renderNotes(view,id,ops,compact=false){const box=node('section',null,'panel workflow-panel');box.append(node('h2','Case notes'),node('p','Latest updates for a quick handover. Add a note while on the phone; recording every conversation is optional.','field-help'));for(const n of (compact?ops.notes.slice(0,3):ops.notes)){box.append(node('p',n.text,'case-note'),node('small',`${n.actor||'Development operator'} · ${new Date(n.at||n.createdAt).toLocaleString('en-AU')}`));}const key='note/'+id,d=drafts.get(key)??{requestId:crypto.randomUUID(),text:'',baseVersion:ops.version};const form=node('form',null,'form-grid');input(form,'New case note',d,'text','textarea').required=true;form.oninput=()=>drafts.set(key,d);const feedback=node('div'),submit=node('button','Add case note','primary');submit.type='submit';submit.dataset.label='Add case note';form.append(feedback,submit);form.onsubmit=e=>{e.preventDefault();drafts.set(key,d);send(form,d,key,`projects/${id}/notes`,'POST',{requestId:d.requestId,text:d.text.trim()},feedback,submit);};if(d.pending){form.querySelector('textarea').disabled=true;submit.textContent='Retry save safely';}box.append(form);if(compact)box.insertBefore(form,box.children[2]??null);if(compact&&ops.notes.length>3)box.append(link('View all case notes','operations/'+id));view.append(box);}
function renderInvoices(view,id,p,ops,payers,business,clients,people,lifecycle,reviewFunding){
 if(!lifecycle.managed&&p.kind==='Assessment'){view.append(notice('Assessments are free. No assessment invoice or payment is required.'));return;}
 const box=node('section',null,'panel workflow-panel');box.append(node('h2','Draft invoices'),notice('Save an itemised draft for review. Recording an invoice does not confirm payment. Financial details and tax treatment come from Settings.'));
 for(const i of ops.invoices)box.append(link((i.number||i.invoiceNumber)+' · '+money(i.totalCents)+' AUD','documents/'+id));
 if(lifecycle.managed&&(lifecycle.state.financeFinalisation||lifecycle.state.closed||p.status==='closed')){box.append(notice('Finance is finalised. Reopen the project through its guided workflow before changing financial records.'));view.append(box);return;}
 const key='invoice/'+id,d=drafts.get(key)??{requestId:crypto.randomUUID(),milestone:'deposit',billingMode:'separate',payer:payers[0][0],invoiceDate:new Intl.DateTimeFormat('sv-SE',{timeZone:'Australia/Adelaide',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),billingAddress:'',lines:[{description:p.title,quantity:'1',unitPrice:''}],milestoneReached:false};
 const form=node('form',null,'form-grid invoice-editor');
 const addressFor=target=>{const[type,recordId]=target.split(':');const clientId=type==='client'?recordId:type==='person'?people.find(x=>x.id===recordId)?.clientId:null;const details=clients.find(c=>c.id===clientId)?.details;return details?.workAddress||details?.residentialAddress||'';};
 if(!drafts.has(key))d.billingAddress=addressFor(d.payer);
 input(form,'Invoice date',d,'invoiceDate','date').required=true;select(form,'Billing milestone',d,'milestone',[['deposit','Deposit'],['progress','Progress'],['final','Final']]);check(form,'Administrator confirms this billing milestone has been reached',d,'milestoneReached');const arrangement=select(form,'Invoice arrangement',d,'billingMode',[['separate','Separate invoice for this payer’s contribution'],['nominated','One nominated payer manages the split']]);
 const contributorKeys=new Set(ops.fundingContributors.map(c=>c.type+':'+c.id));const recipientOptions=()=>{const choices=d.billingMode==='nominated'?[...payers]:payers.filter(([key])=>contributorKeys.has(key));if(!choices.some(([key])=>key===d.payer)){const selected=payers.find(([key])=>key===d.payer);choices.unshift([d.payer,(selected?.[1]||d.payer)+' — draft selection; no saved contribution']);}return choices;};
 const fundingGuide=node('div',null,'message');fundingGuide.setAttribute('role','status');const fundingMessage=node('p'),fundingButton=button('Review payer contributions',()=>{drafts.set(key,d);reviewFunding();});fundingGuide.append(fundingMessage,fundingButton);form.append(fundingGuide);
 const showFundingGuide=()=>{const missing=!contributorKeys.size||(d.billingMode==='separate'&&!contributorKeys.has(d.payer));fundingGuide.hidden=!missing;fundingMessage.textContent=!contributorKeys.size?'Confirm the agreed payer contribution before creating this draft. No payer contributions have been saved. Review the amount with the client or funder, then save case details. Your invoice draft will be kept.':!contributorKeys.has(d.payer)?'The selected invoice recipient has no saved contribution. For a separate invoice, choose a recorded contributor or confirm and save this payer’s agreed contribution. A nominated payer can manage the recorded funding split. Your draft selection has been retained.':'';};
 const recipient=select(form,'Invoice recipient',d,'payer',recipientOptions());arrangement.addEventListener('change',()=>{recipient.replaceChildren(...recipientOptions().map(([value,label])=>{const option=node('option',label);option.value=value;return option;}));recipient.value=d.payer;drafts.set(key,d);showFundingGuide();});const address=input(form,'Billing address',d,'billingAddress','textarea');address.maxLength=500;recipient.addEventListener('change',()=>{d.billingAddress=addressFor(d.payer);address.value=d.billingAddress;drafts.set(key,d);showFundingGuide();});
 const items=node('fieldset');items.append(node('legend','Invoice items'));const rows=node('div',null,'invoice-lines'),totals=node('div',null,'invoice-totals');
 const quantity=value=>{if(!/^\d+(\.\d{1,3})?$/.test(String(value)))throw Error('Quantity needs up to three decimal places.');const q=Math.round(Number(value)*1000);if(!Number.isSafeInteger(q)||q<1)throw Error('Quantity must be greater than zero.');return q;};
 const calculate=()=>{try{const amount=d.lines.reduce((sum,line)=>sum+Math.round(quantity(line.quantity)*cents(line.unitPrice)/1000),0);let gst=0,total=amount;if(business.gstConfirmed&&business.gstMode==='exclusive'){gst=Math.round(amount*business.gstRateBps/10000);total+=gst;}else if(business.gstConfirmed&&business.gstMode==='inclusive')gst=Math.round(amount*business.gstRateBps/(10000+business.gstRateBps));totals.replaceChildren(node('strong','Preview total: $'+money(total)+' AUD'),node('p',business.gstConfirmed?(business.gstMode==='not-registered'?'No GST charged.':'GST component: $'+money(gst)):'Tax treatment is unconfirmed. This preview does not calculate GST.','field-help'));}catch{totals.replaceChildren(node('p','Complete each quantity and unit price to preview the total.','field-help'));}};
 const drawLines=()=>{rows.replaceChildren();d.lines.forEach((line,index)=>{const row=node('div',null,'invoice-line');input(row,'Item '+(index+1)+' description',line,'description').required=true;const q=input(row,'Item '+(index+1)+' quantity',line,'quantity');q.inputMode='decimal';q.required=true;const price=input(row,'Item '+(index+1)+' unit price ($ AUD)',line,'unitPrice');price.inputMode='decimal';price.required=true;line.category??='unclassified';select(row,'Item '+(index+1)+' reporting category',line,'category',[['unclassified','Not classified'],['service_charge','Service charge'],['other','Other charge']]);if(d.lines.length>1)row.append(button('Remove item '+(index+1),()=>{d.lines.splice(index,1);drafts.set(key,d);drawLines();calculate();}));rows.append(row);});};
 const quoteFeedback=node('p',null,'field-help');quoteFeedback.setAttribute('role','status');
 const accepted=lifecycle.state?.quotes?.find(q=>q.version===lifecycle.state.acceptance?.quoteVersion);
 const useQuote=button('Use accepted quote items',()=>{if(!accepted)return;if(accepted.lines.length>10){quoteFeedback.textContent='This quote has '+accepted.lines.length+' items. An invoice supports up to10 items. Create separate drafts or deliberately combine appropriate items; no quote items have been copied or omitted.';return;}if(drafts.has(key)&&!confirm('Replace the current invoice items with the accepted quote? Other invoice details will stay as entered.'))return;d.lines=accepted.lines.map(line=>({description:line.description,quantity:String(line.quantityMilli/1000),unitPrice:money(line.unitPriceCents)}));drafts.set(key,d);drawLines();calculate();quoteFeedback.textContent='Accepted quote version '+accepted.version+' copied into editable invoice items. Review quantities, prices, payer, milestone and tax before creating a draft.';rows.querySelector('input')?.focus();});
 useQuote.disabled=!accepted;items.append(useQuote,quoteFeedback);if(!accepted)quoteFeedback.textContent='Accept a quote in the guided workflow before copying its items.';else if(accepted.lines.length>10)quoteFeedback.textContent='The accepted quote has '+accepted.lines.length+' items; invoices support up to10. Copying will not truncate the quote. Prepare the allocation deliberately.';
 items.append(rows,button('Add invoice item',()=>{if(d.lines.length>=10)return;d.lines.push({description:'',quantity:'1',unitPrice:''});drafts.set(key,d);drawLines();calculate();rows.lastElementChild?.querySelector('input')?.focus();}),totals);drawLines();calculate();form.append(items,node('p','Issuer: '+(business.issuerName||'Not configured')+' · ABN: '+(business.abn||'Not configured'),'field-help'),link('Review issuer and tax settings','settings'));
 const feedback=node('div'),submit=node('button','Create draft invoice','primary');submit.type='submit';submit.dataset.label='Create draft invoice';const actions=node('div',null,'actions');actions.append(submit,button('Discard invoice draft',()=>{drafts.delete(key);host.refresh();}));form.oninput=()=>{drafts.set(key,d);calculate();};form.onchange=()=>{drafts.set(key,d);showFundingGuide();};form.append(feedback,actions);showFundingGuide();
 form.onsubmit=e=>{e.preventDefault();try{if(!d.pending&&d.billingMode==='separate'&&!contributorKeys.has(d.payer)){drafts.set(key,d);showFundingGuide();fundingButton.focus();return;}const[payerType,payerId]=d.payer.split(':');drafts.set(key,d);send(form,d,key,`projects/${id}/invoices`,'POST',{requestId:d.requestId,version:ops.version,milestone:d.milestone,billingMode:d.billingMode,payerType,payerId,invoiceDate:d.invoiceDate,billingAddress:d.billingAddress.trim(),lines:d.lines.map(line=>({description:line.description.trim(),quantityMilli:quantity(line.quantity),unitPriceCents:cents(line.unitPrice),category:line.category??'unclassified'})),milestoneReached:d.milestoneReached},feedback,submit);}catch(e){feedback.replaceChildren(notice(e.message,true));}};
 if(d.pending){form.querySelectorAll('input,select,textarea,button').forEach(n=>n.disabled=n!==submit);submit.textContent='Retry save safely';}box.append(form);view.append(box);
}
function renderDocuments(view,p,ops,lifecycle){view.append(notice('Review before printing. These are provisional internal drafts, not the approved customer forms. No email is sent.'));
  const article=node('article',null,'print-document panel');article.append(node('h2',lifecycle.managed?'TADSA — Project summary':'TADSA — '+(p.kind==='Assessment'?'Assessment Request':'Project Request')),node('strong','DRAFT · Fictional development data'),node('p',p.reference+' · '+p.title),node('p','Client: '+p.clientName),node('p',p.summary),node('p','Technician: '+(p.relationships.find(r=>r.role==='Technician')?.name||'Not assigned')));
  if(lifecycle.managed){const state=lifecycle.state;if(ops.onHold||ops.clientStopped)article.append(node('p',ops.clientStopped?'CLIENT STOP — Work must remain stopped until client consent and authorised resumption are recorded.':'WORK ON HOLD — Do not continue work while this hold remains active.','document-warning'));if(state.revisionRequested)article.append(node('p','QUOTE REVISION PENDING — '+state.revisionRequested.reason+'. Previous approvals do not authorise revised work.','document-warning'));article.append(node('p','Guided stage: '+state.stage.replaceAll('_',' ')),node('p','Assessment: '+(!state.assessmentDecision?'Decision not recorded':state.assessmentDecision.required?(state.assessment?'Completed':'Required — pending'):'Not required — '+state.assessmentDecision.reason)),node('p','Accepted quote: '+(state.acceptance?'Version '+state.acceptance.quoteVersion+' · '+state.acceptance.acceptedBy+' · '+state.acceptance.date:'Not recorded')),node('p','Finance clearance: '+(state.financeClearance?state.financeClearance.status+' · external confirmation '+state.financeClearance.reference+' · '+state.financeClearance.confirmedOn:'Not recorded')),node('p','Work: '+(state.work?.status?.replaceAll('_',' ')||'Not started')),node('p','Customer sign-off: '+(state.signoff?state.signoff.acceptedBy+' · '+state.signoff.signedOn+' · '+state.signoff.reference:'Not recorded')),node('p','Finance finalisation: '+(state.financeFinalisation?state.financeFinalisation.reference+' · '+state.financeFinalisation.confirmedOn:'Not recorded')));if(state.cancellation)article.append(node('p','Cancellation: '+state.cancellation.reason));}
  else article.append(node('p','Historical assessment: '+(ops.assessmentComplete?'Recorded complete':'Pending')),node('p','Historical work approval: '+(ops.workApproved?(ops.approvedByName||'Previous approver entry')+' · '+ops.approvedOn:'Not recorded')));
  article.append(node('p','Actual hours: '+ops.actualMinutes/60+' · Estimated hours remaining: '+ops.remainingMinutes/60));view.append(article);

  for (const i of ops.invoices) {
    const business=i.business||{}, inv=node('article',null,'print-document panel invoice-document');
    const brand=node('header',null,'invoice-brand'), logo=node('img');
    logo.src='./assets/tadsa-logo.png';logo.alt='TADSA';logo.width=234;logo.height=45;
    brand.append(logo,node('span',i.documentLabel||'Draft invoice'));inv.append(brand);
    const heading=node('div',null,'invoice-heading');
    heading.append(node('h2',i.number||i.invoiceNumber),node('p','Invoice date: '+(i.invoiceDate||'Not recorded')),node('strong','DRAFT · Fictional development data'));inv.append(heading);
    const parties=node('div',null,'invoice-parties'),issuer=node('section'),recipient=node('section');
    issuer.append(node('h3','From'),node('strong',business.issuerName||'Issuer not configured'),node('p','ABN: '+(business.abn||'Not configured')),node('p',business.address||'Address not configured'),node('p',business.contact||'Contact not configured'));
    recipient.append(node('h3','Bill to'),node('strong',i.payerName||i.payerId||'Recipient not recorded'),node('p',i.billingAddress||'Billing address not recorded'),node('p',i.projectReference+' · '+i.projectTitle),node('p','Milestone: '+i.milestone));parties.append(issuer,recipient);inv.append(parties);
    const table=node('table',null,'invoice-table'),thead=node('thead'),head=node('tr');
    const labels=['Description','Quantity','Unit price','Amount'];
    for(const text of labels){const th=node('th',text);th.scope='col';head.append(th);}thead.append(head);table.append(thead);
    const body=node('tbody');
    for(const line of i.lines||[]){
      const row=node('tr');
      const values=[line.description,line.quantityMilli===undefined?'1':String(line.quantityMilli/1000),'$'+money(line.unitPriceCents??line.amountCents),'$'+money(line.amountCents)];
      for(const [index,value] of values.entries()){
        const td=node('td');td.dataset.label=labels[index];
        const label=node('span',labels[index],'invoice-mobile-label');label.setAttribute('aria-hidden','true');
        td.append(label,node('span',value));row.append(td);
      }
      body.append(row);
    }
    table.append(body);inv.append(table);
    const total=node('div',null,'invoice-totals');
    if(i.subtotalCents!==undefined)total.append(node('p','Subtotal: $'+money(i.subtotalCents)));
    total.append(node('p',business.gstConfirmed?'GST: $'+money(i.gstCents||0):'Tax treatment unconfirmed'),node('strong','Total: $'+money(i.totalCents)+' AUD'));inv.append(total);
    for(const warning of i.readinessWarnings||[])inv.append(node('p',warning,'document-warning'));
    inv.append(node('p','Payment terms: '+(business.paymentTerms||'Not configured')),node('p','Payment details: '+(business.bankDetails||'Not configured')),node('p','Saved invoice snapshot. This document does not confirm receipt of payment.','field-help'));view.append(inv);
  }
  view.append(button('Print / save as PDF',()=>window.print()));
}
