let host;
const drafts=new Map();
const openSections=new Map();
function rememberSection(section,key){section.open=openSections.get(key)??false;section.addEventListener('toggle',()=>{openSections.set(key,section.open);if(section.open&&matchMedia('(max-width:800px)').matches){for(const other of section.parentElement?.children??[])if(other!==section&&other.tagName==='DETAILS')other.open=false;}});}
export const configureCare=h=>{host=h;};
export const careHasDrafts=()=>drafts.size>0;
export const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
export const action=(text,fn)=>{const b=node('button',text,'secondary');b.type='button';b.onclick=fn;return b;};
export const link=(text,hash)=>{const a=node('a',text,'button secondary');a.href='#'+hash;return a;};
export const notice=(text,error=false)=>{const p=node('p',text,error?'message error':'message');p.setAttribute('role',error?'alert':'status');return p;};
export async function request(path,method='GET',body){const r=await fetch('/api/'+path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok){const e=Error(data.error);e.status=r.status;throw e;}return data;}
export function field(parent,label,d,key,type='text',options){const l=node('label',null,'workflow-field');l.append(node('span',label,'field-label'));const n=node(options?'select':type==='textarea'?'textarea':'input');n.setAttribute('aria-label',label);if(options){for(const[value,text]of options){const o=node('option',text);o.value=value;n.append(o);}}else if(type!=='textarea')n.type=type;if(type==='checkbox'){n.checked=Boolean(d[key]);l.className='checkbox';}else n.value=d[key]??'';if(type==='text')n.maxLength=200;if(type==='textarea'){n.rows=3;n.maxLength=500;}n.addEventListener(options||type==='checkbox'?'change':'input',()=>d[key]=type==='checkbox'?n.checked:n.value);l.append(n);parent.append(l);return n;}
export function editor(parent,key,initial,title,fields,path,method,payload){
 const d=drafts.get(key)??{...initial,requestId:crypto.randomUUID()},box=node('section',null,'panel workflow-panel'),form=node('form',null,'form-grid');if(title)box.append(node('h2',title));box.append(form);parent.append(box);fields(form,d);const feedback=node('div'),buttons=node('div',null,'actions'),save=node('button','Save','primary');save.type='submit';const discard=action('Discard unsaved changes',()=>{drafts.delete(key);host.refresh();});buttons.append(save,discard);form.append(feedback,buttons);const remember=()=>drafts.set(key,d);form.addEventListener('input',remember);form.addEventListener('change',remember);
 const lock=()=>{form.querySelectorAll('input,select,textarea,button').forEach(n=>n.disabled=Boolean(d.pending)&&n!==save);save.textContent=d.pending?'Retry save safely':(save.dataset.label||'Save');};lock();
 form.onsubmit=async e=>{e.preventDefault();if(host.isSaving())return;host.setSaving(true);form.querySelectorAll('input,select,textarea,button').forEach(n=>n.disabled=true);try{d.pending??=await payload(d);remember();feedback.replaceChildren(notice('Saving…'));await request(path,method,d.pending);window.dispatchEvent(new Event('tadsa-saved'));drafts.delete(key);host.setSaving(false);host.refresh();}catch(error){if(error.status){d.pending=null;d.requestId=crypto.randomUUID();}feedback.replaceChildren(notice(error.message||'Save not confirmed. Retry safely.',true));if(error.status===409)feedback.append(notice('Discard this draft to load the latest saved version, then reapply your change.'));}finally{host.setSaving(false);lock();}};
 return {form,d,box};
}
const dollars=c=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format((c||0)/100);
export async function renderProjectCare(view,id,summaryTarget=view){
 const [plan,attachments,ops,options,location,approvers]=await Promise.all([request(`projects/${id}/work-plan`),request(`projects/${id}/attachments`),request(`projects/${id}/operations`),request('availability-options'),request(`projects/${id}/location`),request('approvers')]);
 const summary=node('section',null,'panel care-summary');summary.append(node('h2',plan.assessmentFree?'Free assessment':'Before work begins'),notice(plan.workGate.allowed?'Payment, NDIS and hold checks are clear. Assessment completion and administrator work approval are recorded in the case workspace.':plan.workGate.reasons.join(' ')),node('p',`Labour: ${dollars(plan.labourRateCents)}/hour · Actual ${dollars(plan.actualLabourCents)} · Estimated remaining ${dollars(plan.remainingLabourCents)}`));const locationText=[location.address,location.suburb,location.postcode].filter(Boolean).join(', ');if(locationText){summary.append(node('p','Location: '+locationText));const map=node('a','Open location in maps','button secondary');map.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(locationText);map.target='_blank';map.rel='noopener noreferrer';summary.append(map);}summary.querySelector('.message').classList.toggle('warning',!plan.workGate.allowed);summary.classList.add('compact-care-summary');summary.append(link('Hours, approval & draft invoices','operations/'+id));summaryTarget.append(summary);
 const locationSection=node('details',null,'care-details');locationSection.append(node('summary','Work location'));rememberSection(locationSection,id+'/location');view.append(locationSection);
 editor(locationSection,'location/'+id,location,'Work location',(form,d)=>{field(form,'Work location / address',d,'address');field(form,'Suburb or town',d,'suburb');const postcode=field(form,'Postcode',d,'postcode');postcode.inputMode='numeric';postcode.maxLength=4;field(form,'Service area',d,'serviceArea','text',[['','Not specified'],...[...options.serviceAreas].sort((a,b)=>a.label.localeCompare(b.label,'en-AU')).map(a=>[a.id,a.label])]);form.append(node('p','Use a service area or postcode to compare technician coverage. This is not a distance estimate.','field-help'));},`projects/${id}/location`,'PUT',d=>Object.fromEntries(['requestId','version','address','suburb','postcode','serviceArea'].map(k=>[k,d[k]])));
 const details=node('details',null,'care-details');details.append(node('summary','NDIS funding and approval'));rememberSection(details,id+'/ndis');view.append(details);
 editor(details,'plan/'+id,plan,'NDIS funding and approval',(form,d)=>{field(form,'NDIS funded project',d,'ndisApplicable','checkbox');field(form,'Client NDIS number',d,'ndisNumber').inputMode='numeric';form.append(node('p','The client number is shared across their projects. Approval applies to this project.','field-help'));field(form,'NDIS approval received',d,'ndisApproved','checkbox');const values=[['','Choose an administrator'],...approvers.items.map(a=>[a.id,a.name])];if(d.ndisApprovedBy&&!approvers.items.some(a=>a.id===d.ndisApprovedBy))values.push([d.ndisApprovedBy,'Previous entry — choose an administrator']);field(form,'NDIS approval recorded by',d,'ndisApprovedBy','text',values);field(form,'NDIS approval date',d,'ndisApprovedOn','date');},`projects/${id}/work-plan`,'PUT',d=>Object.fromEntries(['requestId','version','clientNdisVersion','location','serviceArea','ndisApplicable','ndisNumber','ndisApproved','ndisApprovedBy','ndisApprovedOn'].map(k=>[k,d[k]])));
 const payments=node('details',null,'care-details');payments.append(node('summary','Invoices and payment received'));rememberSection(payments,id+'/payments');payments.append(node('p','Record receipt after checking payment. This does not charge a card or connect to a bank. Technical work requires at least one invoice and all recorded invoices paid in full. Assessments are free.'));view.append(payments);
 if(!ops.invoices.length)payments.append(link('Create a draft invoice','operations/'+id));
 for(const invoice of ops.invoices){const i={...invoice,...invoice.snapshot},received=(plan.payments||[]).filter(p=>p.invoiceId===invoice.id).reduce((n,p)=>n+p.amountCents,0);const box=node('section',null,'panel');box.append(node('h3',i.number),node('p',`Invoice ${dollars(i.totalCents)} · Received ${dollars(received)} · Outstanding ${dollars(i.totalCents-received)}`));payments.append(box);if(received>=i.totalCents)continue;editor(box,'payment/'+invoice.id,{version:plan.version,amount:((i.totalCents-received)/100).toFixed(2),receivedOn:new Date().toISOString().slice(0,10),reference:''},'Record payment',(f,d)=>{field(f,'Payment amount ($ AUD)',d,'amount').inputMode='decimal';field(f,'Payment received on',d,'receivedOn','date').required=true;field(f,'Payment reference',d,'reference').required=true;},`projects/${id}/invoices/${invoice.id}/payments`,'POST',d=>{if(!/^\d+(\.\d{1,2})?$/.test(d.amount))throw Error('Enter a dollar amount with up to two decimal places.');return {requestId:d.requestId,version:d.version,amountCents:Math.round(Number(d.amount)*100),receivedOn:d.receivedOn,reference:d.reference};});}
 const files=node('details',null,'care-details project-files');files.append(node('summary','Project files'),node('p',`Images and documents · ${attachments.items.length} of ${attachments.maxFiles} files · up to ${Math.floor(attachments.maxBytes/1024/1024)} MB per file.`,'field-help'));rememberSection(files,id+'/files');view.append(files);
 for(const file of attachments.items){const row=node('div',null,'file-row');row.append(node('span',`${file.name} · ${Math.ceil(file.size/1024)} KB`));const feedback=node('div');row.append(action('Download',async()=>{try{const response=await fetch(`/api/projects/${id}/attachments/${file.id}/download`);if(!response.ok)throw Error('Could not download file.');const url=URL.createObjectURL(await response.blob()),a=node('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){feedback.replaceChildren(notice(e.message,true));}}));const removal=node('details');removal.append(node('summary','Remove file'));editor(removal,'remove/'+file.id,{version:file.version},null,(f)=>f.append(node('p','Remove '+file.name+' from this project?')),`projects/${id}/attachments/${file.id}/remove`,'POST',d=>({requestId:d.requestId,version:d.version}));row.append(removal,feedback);files.append(row);}
 editor(files,'upload/'+id,{},'Add image or document',(form,d)=>{const f=field(form,'Choose file (PNG, JPEG, PDF or DOCX)',{},'file','file');f.accept='.png,.jpg,.jpeg,.pdf,.docx';f.required=!d.pending&&!d.file;if(d.file)form.append(node('p','Selected file: '+d.file.name));f.onchange=()=>{d.file=f.files[0];};},`projects/${id}/attachments`,'POST',async d=>{if(!d.file)throw Error('Choose a file first.');if(d.file.size>attachments.maxBytes)throw Error('File exceeds the 10 MB limit.');const file=d.file,mime=(file.type==='image/jpg'?'image/jpeg':file.type)||({pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}[file.name.split('.').pop().toLowerCase()]);const dataBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Unable to read file.'));reader.readAsDataURL(file);});return {requestId:d.requestId,name:file.name,mime,dataBase64};});
}
