import {renderReportBuilder} from './report-builder.js';
import {node,link,request,notice,action} from './project-care.js';
let selectedMonth;
const money=c=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format((c||0)/100);
const date=value=>value?new Date(value).toLocaleDateString('en-AU',{timeZone:'Australia/Adelaide',day:'numeric',month:'short',year:'numeric'}):'Not recorded';
async function renderMonthlyReports(view){
 if(!selectedMonth){const p=Object.fromEntries(new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Adelaide',year:'numeric',month:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));selectedMonth=p.year+'-'+p.month;}
 view.append(node('h2','Monthly overview'),node('p','Monthly activity, current open work and recorded billing. Reporting dates use Adelaide time.','subtitle'));
 const toolbar=node('form',null,'report-toolbar panel'),label=node('label',null,'workflow-field'),month=node('input');label.append(node('span','Reporting month','field-label'));month.type='month';month.value=selectedMonth;month.required=true;month.setAttribute('aria-label','Reporting month');label.append(month);const submit=node('button','Run report','primary');submit.type='submit';toolbar.append(label,submit);view.append(toolbar);const output=node('div');output.setAttribute('aria-live','polite');view.append(output);let ticket=0;
 function projects(title,group,explanation){const section=node('details',null,'care-details report-section');section.append(node('summary',`${title} · ${group.count}`));if(explanation)section.append(node('p',explanation,'field-help'));if(group.eventCount!==undefined&&group.eventCount!==group.count)section.append(node('p',`${group.eventCount} recorded events across ${group.count} projects.`));if(group.unknownHistoricalCount)section.append(notice(`${group.unknownHistoricalCount} historical records have no tracked date. They are not assigned to this month.`));for(const p of group.items||[]){const row=node('div',null,'report-row');row.append(link((p.reference?p.reference+' · ':'')+p.title,'project/'+p.id),node('span',[p.status,date(p.at)].filter(Boolean).join(' · '),'field-help'));section.append(row);}if(!group.items?.length)section.append(node('p',group.count?'Matching projects are outside this displayed activity window.':'No matching projects.','field-help'));return section;}
 async function load(){const current=++ticket;selectedMonth=month.value;output.setAttribute('aria-busy','true');output.replaceChildren(node('p','Loading report…','loading'));try{const report=await request('reports?month='+encodeURIComponent(selectedMonth));if(current!==ticket||!view.isConnected)return;output.replaceChildren();if(report.detailNotice)output.append(notice(report.detailNotice));output.append(node('h2',new Date(report.month+'-01T12:00:00').toLocaleDateString('en-AU',{month:'long',year:'numeric'})));
  const summary=node('section',null,'panel report-summary');summary.append(node('h3','At a glance'));for(const [label,value]of[['Created this month',report.created.count],['Closed this month',report.closed.count],['Currently open',report.currentOpen.count],['Draft invoices recorded',money(report.billing.invoicedCents)],['Receipts recorded',money(report.billing.receivedCents)]]){const item=node('div');item.append(node('span',label,'field-label'),node('strong',String(value)));summary.append(item);}output.append(summary);
  output.append(projects('Projects created',report.created,'Based on recorded creation events. Older imported records without creation history are reported separately.'),projects('Projects closed',report.closed,'Projects with a closure event in this month, including those reopened later.'),projects('Projects reopened',report.reopened),projects('Currently open projects',report.currentOpen,'Current position, regardless of the selected month.'));
  const workload=node('section',null,'panel');workload.append(node('h2','Current lead technician workload'));for(const t of report.workload){const row=node('div',null,'report-row');row.append(link(t.name,'person/'+t.id),node('span',`${t.projectCount} projects · ${(t.remainingMinutes/60).toFixed(1)} hours remaining`));workload.append(row);}if(!report.workload.length)workload.append(node('p','No technician workload recorded.'));output.append(workload,node('p','Recorded receipts are not a bank reconciliation. Draft invoice totals do not confirm payment or permission to start work.','field-help'),action('Print / save report as PDF',()=>window.print()));
 }catch(e){if(current===ticket)output.replaceChildren(notice(e.message||'Report unavailable. Try again.',true));}finally{if(current===ticket)output.removeAttribute('aria-busy');}}
 toolbar.onsubmit=e=>{e.preventDefault();if(month.reportValidity())load();};await load();
}

export async function renderReports(view){
 view.append(node('h1','Reports'));
 const nav=node('div',null,'record-tabs'),body=node('div');let cleanup;
 const builder=action('Build a report',()=>open('builder')),monthly=action('Monthly overview',()=>open('monthly'));nav.append(builder,monthly);view.append(nav,body);
 function open(mode){cleanup?.();cleanup=null;body.replaceChildren();builder.setAttribute('aria-pressed',String(mode==='builder'));monthly.setAttribute('aria-pressed',String(mode==='monthly'));if(mode==='builder')cleanup=renderReportBuilder(body);else renderMonthlyReports(body).catch(error=>body.replaceChildren(notice(error.message,true)));}
 open('builder');
}
