import {renderReportBuilder} from './report-builder.js';
import {managementReportCsv} from './management-report.js';
import {node,link,request,notice,action} from './project-care.js';
let selectedMonth,selectedMode='builder';
const money=c=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(c/100);
const value=m=>m.value===null?'Not fully recorded':m.unit==='currency'?money(m.value):new Intl.NumberFormat('en-AU',{maximumFractionDigits:2}).format(m.value)+(m.unit==='hours'?' hrs':'');
async function renderMonthlyReports(view){
 if(!selectedMonth){const p=Object.fromEntries(new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Adelaide',year:'numeric',month:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));selectedMonth=p.year+'-'+p.month;}
 view.append(node('h2','Monthly management overview'),node('p','Project outcomes, Freedom Wheels, feedback and current technical members. Open a measure to see its definition and contributing records.','subtitle'));
 const toolbar=node('form',null,'report-toolbar panel'),label=node('label',null,'workflow-field'),month=node('input');label.append(node('span','Reporting month','field-label'));month.type='month';month.value=selectedMonth;month.required=true;month.setAttribute('aria-label','Reporting month');label.append(month);const submit=node('button','Run report','primary');submit.type='submit';toolbar.append(label,submit);view.append(toolbar);const output=node('div');output.setAttribute('aria-live','polite');view.append(output);let ticket=0;
 async function load(){const current=++ticket;selectedMonth=month.value;output.setAttribute('aria-busy','true');output.replaceChildren(node('p','Loading report…','loading'));try{
  const report=await request('reports?month='+encodeURIComponent(selectedMonth));if(current!==ticket||!view.isConnected)return;
  const management=report.management;output.replaceChildren(node('h2',new Date(report.month+'-01T12:00:00').toLocaleDateString('en-AU',{month:'long',year:'numeric'})),node('p',management.notice,'field-help'));
  for(const group of management.groups){const section=node('section',null,'panel management-report-group');section.append(node('h3',group.label));
   const table=node('table',null,'management-report-table'),head=node('thead'),header=node('tr');for(const title of ['Measure','Total']){const th=node('th',title);th.scope='col';header.append(th);}head.append(header);table.append(head);const body=node('tbody');
   for(const m of group.metrics){const row=node('tr');row.dataset.metric=m.key;const cell=node('td'),detail=node('details',null,'management-metric');detail.append(node('summary',m.label),node('p',m.definition,'field-help'));
    if(m.missingCount)detail.append(notice(`${m.missingCount} record(s) need more information. Known portion: ${value({...m,value:m.knownValue})}.`));
    for(const p of m.items){const destination=m.key==='activeTechnicians'?'person/':'project/';detail.append(link([p.reference,p.title].filter(Boolean).join(' · '),destination+p.id));}
    if(m.count>m.items.length)detail.append(node('p',`Showing ${m.items.length} of ${m.count} contributing records. The total includes all matching records.`,'field-help'));
    if(!m.count)detail.append(node('p','No contributing records.','field-help'));cell.append(detail);const total=node('td',value(m),'management-metric-value');total.dataset.value=m.value===null?'unknown':String(m.value);row.append(cell,total);body.append(row);
   }table.append(body);section.append(table);output.append(section);
  }
  const coverage=node('details',null,'care-details');coverage.append(node('summary','Data coverage and reporting basis'),node('p','Months use Adelaide time for timestamped events and the explicitly entered date for sent quotes, final delivery and feedback. Older unknown values are not inferred.','field-help'));
  const c=management.coverage;for(const text of [`${c.unknownCreation} projects have no recorded creation event.`,`${c.unknownClosure} closed projects have no recorded closure event and cannot be assigned to a month.`,`${c.missingDelivery} completed Freedom Wheels projects have no explicit final delivery date/quantity and are excluded from delivery totals; their delivery month is unknown.`,`${c.unknownProgramme} projects have no programme recorded; they remain in all-project figures but are not assumed to be Freedom Wheels.`,`${c.unclassifiedFeedback} feedback entries this month have no completion classification.`,`${c.legacyProgrammeEvents} historical workflow events lack an event-time programme; their current project programme is used. Historical totals can change after corrections.`])coverage.append(node('p',text,'field-help'));output.append(coverage);
  const extra=node('details',null,'care-details');extra.append(node('summary','Other monthly activity and current workload'),node('p',`Reopened this month: ${report.reopened.count} · Currently open: ${report.currentOpen.count}`),node('p',`Draft invoices dated in this month: ${money(report.billing.invoicedCents)} · Receipts dated in this month: ${money(report.billing.receivedCents)}`),node('p','These billing-date totals answer a different question from whole-project totals above. Receipts are not a bank reconciliation.','field-help'));
  for(const [label,group]of [['Reopened projects',report.reopened],['Currently open projects',report.currentOpen]]){extra.append(node('h3',label));for(const p of group.items)extra.append(link(p.reference+' · '+p.title,'project/'+p.id));}
  extra.append(node('h3','Current lead technician workload'));for(const t of report.workload){const row=node('div',null,'report-row');row.append(link(t.name,'person/'+t.id),node('span',`${t.projectCount} projects · ${t.remainingMinutes==null?'Remaining work: Not recorded':(t.remainingMinutes/60).toFixed(1)+' hours'+(t.remainingWorkUnrecordedCount?' recorded; '+t.remainingWorkUnrecordedCount+' project'+(t.remainingWorkUnrecordedCount===1?'':'s')+' not estimated':' remaining')}`));extra.append(row);}extra.append(node('p',report.detailNotice,'field-help'));output.append(extra);
  const actions=node('div',null,'actions');actions.append(action('Download summary CSV',()=>{const url=URL.createObjectURL(new Blob([managementReportCsv(management)],{type:'text/csv;charset=utf-8'}));const a=node('a');a.href=url;a.download='tadsa-management-'+report.month+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}),action('Print / save report as PDF',()=>window.print()));output.append(actions);
 }catch(e){if(current===ticket)output.replaceChildren(notice(e.message||'Report unavailable. Try again.',true));}finally{if(current===ticket)output.removeAttribute('aria-busy');}}
 toolbar.onsubmit=e=>{e.preventDefault();if(month.reportValidity())load();};await load();
}
export async function renderReports(view){
 view.append(node('h1','Reports'));const nav=node('div',null,'record-tabs'),body=node('div');let cleanup;
 const builder=action('Build a report',()=>open('builder')),monthly=action('Monthly overview',()=>open('monthly'));nav.append(builder,monthly);view.append(nav,body);
 function open(mode){selectedMode=mode;cleanup?.();cleanup=null;body.replaceChildren();builder.setAttribute('aria-pressed',String(mode==='builder'));monthly.setAttribute('aria-pressed',String(mode==='monthly'));if(mode==='builder')cleanup=renderReportBuilder(body);else renderMonthlyReports(body).catch(error=>body.replaceChildren(notice(error.message,true)));}open(selectedMode);
}
