import {node,request,field,editor,action,notice} from './project-care.js';
let host;
export const configureSettings=value=>{host=value;};
const backupDrafts=new Map();
const preferenceKey='tadsa-preferences-v1';
const money=cents=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(cents/100);
export async function renderSettings(view){
 view.append(node('h1','Settings'),node('p','Manage the workspace rate and make this device comfortable to use.','subtitle'));
 const appearance=node('section',null,'panel workflow-panel');appearance.append(node('h2','Appearance'),node('p','These preferences apply only to this browser. Changes take effect immediately.','field-help'));const form=node('div',null,'form-grid');appearance.append(form);view.append(appearance);
 let saved={};try{saved=JSON.parse(localStorage.getItem(preferenceKey)||'{}')||{};}catch{}
 const preferences={theme:['system','light','dark'].includes(saved.theme)?saved.theme:'system',motion:['system','reduced'].includes(saved.motion)?saved.motion:'system'};
 const theme=field(form,'Colour theme',preferences,'theme','text',[['system','Use device setting'],['light','Light'],['dark','Dark']]);
 const motion=field(form,'Animations',preferences,'motion','text',[['system','Respect device preference'],['reduced','Reduce motion']]);
 const feedback=node('p',null,'field-help');feedback.setAttribute('role','status');form.append(feedback);
 const apply=()=>{try{localStorage.setItem(preferenceKey,JSON.stringify(preferences));window.dispatchEvent(new Event('tadsa-preferences'));feedback.textContent='Appearance saved on this device.';}catch{document.documentElement.dataset.theme=preferences.theme==='dark'||preferences.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.motion=preferences.motion==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches?'reduced':'standard';feedback.textContent='Appearance changed for this visit. Browser storage could not save the preference.';}};
 theme.addEventListener('change',apply);motion.addEventListener('change',apply);
 const settings=await request('settings');
 const {form:rateForm}=editor(view,'application-settings',{version:settings.version,rate:(settings.labourRateCents/100).toFixed(2)},'Labour rate',(form,d)=>{form.append(node('strong',money(settings.labourRateCents)+' per hour'),node('p','The default is copied to new projects. Existing projects keep their saved rate; previous invoices remain unchanged. Assessments are free.','field-help'));const rate=field(form,'Hourly labour rate ($ AUD)',d,'rate');rate.inputMode='decimal';rate.required=true;rate.maxLength=9;form.append(node('p','This changes the workspace default for all administrators. It does not reprice existing work.','field-help'));},'settings','PUT',d=>{if(!/^\d+(\.\d{1,2})?$/.test(d.rate))throw Error('Enter a positive dollar amount with up to two decimal places.');const labourRateCents=Math.round(Number(d.rate)*100);if(!Number.isSafeInteger(labourRateCents)||labourRateCents<1||labourRateCents>10000000)throw Error('Enter a rate between $0.01 and $100,000.00.');return {requestId:d.requestId,version:d.version,labourRateCents};});
 const saveButton=rateForm.querySelector('button[type=submit]');saveButton.dataset.label='Save hourly rate';if(!saveButton.textContent.startsWith('Retry'))saveButton.textContent='Save hourly rate';
 if(settings.audit.length){const history=node('details',null,'care-details');history.append(node('summary','Rate change history'));for(const entry of settings.audit){history.append(node('p',`${money(entry.fromRateCents)} → ${money(entry.toRateCents)} · ${new Date(entry.at).toLocaleString('en-AU')} · ${entry.actor}`));}view.append(history);}
 const business=await request('business-settings');
 const initial={...business,issuerName:business.issuerName||'TECHNOLOGY FOR AGEING AND DISABILITY (SA) INC.',abn:business.abn||'90 797 478 904',gstRate:((business.gstRateBps??1000)/100).toFixed(2)};
 const businessSection=node('details',null,'care-details');businessSection.append(node('summary','Invoice issuer and financial details'));view.append(businessSection);
 editor(businessSection,'business-settings',initial,'Invoice issuer',(form,d)=>{field(form,'Legal issuer name',d,'issuerName').required=true;field(form,'ABN',d,'abn');field(form,'Issuer address',d,'address','textarea');field(form,'Issuer contact details',d,'contact','textarea');field(form,'Payment terms',d,'paymentTerms','textarea');field(form,'Bank / payment instructions',d,'bankDetails','textarea');field(form,'GST treatment',d,'gstMode','text',[['unconfirmed','Not confirmed'],['not-registered','Not registered — no GST'],['inclusive','Prices include GST'],['exclusive','Add GST to prices']]);const rate=field(form,'GST rate (%)',d,'gstRate');rate.inputMode='decimal';field(form,'I have confirmed the GST treatment for this organisation',d,'gstConfirmed','checkbox');form.append(node('p','The legal name and ABN are prefilled from TADSA’s published financial report. Confirm all financial settings before issuing invoices. Bank details and tax status are not inferred. Saved invoices retain their original snapshot.','field-help'));},'business-settings','PUT',d=>{if(!/^\d+(\.\d{1,2})?$/.test(d.gstRate))throw Error('Enter a GST percentage with up to two decimal places.');const gstRateBps=d.gstMode==='not-registered'?0:Math.round(Number(d.gstRate)*100);return Object.fromEntries(['requestId','version','issuerName','abn','address','contact','paymentTerms','bankDetails','gstMode','gstConfirmed'].map(k=>[k,k==='abn'?d.abn.replace(/\s/g,''):d[k]]).concat([['gstRateBps',gstRateBps]]));});
 await renderBackups(view);
}

async function renderBackups(view){
 const backups=await request('backups'),section=node('section',null,'panel workflow-panel');section.append(node('h2','Backup and restore'),node('p',backups.capabilities.import?'Device backups contain this browser’s saved demonstration records and files. Keep exported backups private.':'Create and download a backup before important changes. Restore first prepares and checks a separate candidate, then requires an explicit replacement decision.','field-help'));view.append(section);
 editor(section,'backup-create',{},'Create a backup',form=>form.append(node('p','Capture the current workspace. Existing data stays in place.','field-help')),'backups','POST',d=>({requestId:d.requestId}));
 if(backups.capabilities.import){editor(section,'backup-import',{},'Import a device backup',(form,d)=>{const f=field(form,'Choose an exported JSON backup',{},'file','file');f.accept='.json,application/json';f.required=!d.file&&!d.pending;f.onchange=()=>{d.file=f.files[0];};if(d.file)form.append(node('p',d.file.name));},'backups/import','POST',async d=>{if(!d.file)throw Error('Choose a backup file.');if(d.file.size>256*1024*1024)throw Error('Backup exceeds the 256 MB import limit. Your workspace has not changed.');let data;try{data=JSON.parse(await d.file.text());}catch{throw Error('This file is not readable JSON. Your current workspace has not changed.');}return {requestId:d.requestId,name:d.file.name,data};});}
 if(!backups.items.length)section.append(node('p','No backups recorded yet.','field-help'));
 for(const backup of backups.items){const item=node('article',null,'backup-item');item.append(node('h3',backup.name),node('p',`${new Date(backup.createdAt).toLocaleString('en-AU')} · ${Math.ceil(backup.size/1024)} KB`));const tools=node('div',null,'actions'),feedback=node('div');feedback.setAttribute('role','status');item.append(tools,feedback);section.append(item);
  tools.append(action('Download backup',async()=>{try{const r=await fetch('/api/backups/'+encodeURIComponent(backup.id)+'/download');if(!r.ok)throw Error('Backup download failed.');const url=URL.createObjectURL(await r.blob()),a=node('a');a.href=url;a.download=backup.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){feedback.replaceChildren(notice(e.message,true));}}));
  const state=backupDrafts.get(backup.id)??{};backupDrafts.set(backup.id,state);
  const run=async(button,key,path,payload,done)=>{if(host.isSaving())return;host.setSaving(true);button.disabled=true;state[key]??={requestId:crypto.randomUUID(),...payload};if(key==='preview')feedback.replaceChildren(notice('Preparing and checking restore candidate…'));else feedback.prepend(notice('Restoring the selected backup…'));try{const result=await request(path,'POST',state[key]);delete state[key];done(result);}catch(e){if(e.status)delete state[key];if(key==='preview')feedback.replaceChildren(notice(e.message||'Result not confirmed. Retry the same action safely.',true));else feedback.prepend(notice(e.message||'Result not confirmed. Retry the same action safely.',true));button.textContent=state[key]?'Retry safely':key==='preview'?'Preview restore':'Restore this backup';}finally{host.setSaving(false);button.disabled=false;}};
  function showPreview(preview){feedback.replaceChildren();if(!preview.ready){feedback.append(notice('This backup did not pass the restore checks.',true));return;}feedback.append(node('h4','Restore preview ready'));const counts=node('dl',null,'review-list');for(const [name,count]of Object.entries(preview.counts||{})){counts.append(node('dt',name),node('dd',String(count)));}feedback.append(counts);const label=node('label',null,'checkbox'),confirm=node('input');confirm.type='checkbox';label.append(confirm,node('span','Replace the current workspace with this backup. Current unsaved changes will be discarded.'));feedback.append(label);const activate=action('Restore this backup',()=>{if(!confirm.checked){confirm.focus();return;}run(activate,'activate','backups/restore/'+encodeURIComponent(preview.previewId)+'/activate',{confirm:true},result=>{if(!result.restored)throw Error('Restore did not complete.');window.dispatchEvent(new Event('tadsa-workspace-restored'));location.reload();});});activate.disabled=true;confirm.onchange=()=>activate.disabled=!confirm.checked;feedback.append(activate);}
  const preview=action('Preview restore',()=>run(preview,'preview','backups/'+encodeURIComponent(backup.id)+'/restore-preview',{},result=>{state.result=result;showPreview(result);}));tools.append(preview);if(state.result)showPreview(state.result);
 }
}
