import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,extname,sep} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright'),root=fileURLToPath(new URL('../',import.meta.url));
const server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(!path.startsWith('/TADSA-web/'))throw Error();path=path.slice('/TADSA-web'.length);if(path==='/')path='/index.html';const file=resolve(root,'.'+decodeURIComponent(path));if(!file.startsWith(resolve(root)+sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'})[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE_PATH?{executablePath:process.env.BROWSER_EXECUTABLE_PATH}:{})});const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=`http://127.0.0.1:${server.address().port}/TADSA-web/`;await page.goto(base);await page.getByRole('heading',{name:'Projects',exact:true}).waitFor();
 for(const [route,heading]of [['clients','Clients'],['people','People'],['organisations','Organisations'],['client/client-1','Eleanor Walsh'],['project/project-1','Adjustable art station'],['operations/project-1','Case workspace'],['documents/project-1','Project documents']]){await page.goto(base+'#'+route);await page.getByRole('heading',{name:heading,exact:true}).waitFor({timeout:5000}).catch(async e=>{console.log(await page.locator('#content').innerText(),errors);console.log(await page.evaluate(async()=>{try{const m=await import('./operations.js');await m.renderOperations(document.createElement('div'),'operations','project-1');return 'ok';}catch(e){return e.stack;}}));throw e;});assert.equal(await page.locator('.message.error').count(),0);}
 console.log('PASS shared register, client, project, operations and document routes under GitHub Pages prefix');
 for(const route of ['availability','operations/project-1']){await page.goto(base+'#'+route);await page.waitForTimeout(150);assert.equal(await page.locator('.message.error').count(),0);}
 const save=await page.evaluate(async()=>{const api=async(path,method='GET',body)=>{const r=await fetch('/api/'+path,{method,...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};let p=(await api('projects/project-1')).body;const saved=await api('projects/project-1','PATCH',{version:p.version,title:'Persistent offline art station',status:p.status,feedbackRequired:p.feedbackRequired,invoiceRequired:p.invoiceRequired});const c=await api('clients','POST',{requestId:crypto.randomUUID(),name:'Device Example',email:'device@example.invalid',phone:'',allowDuplicate:false});const calendar=await api('availability/person-3/entries','POST',{requestId:crypto.randomUUID(),id:null,version:0,startDate:'2026-10-01',endDate:'2026-10-03',status:'unavailable',note:'Fictional leave'});const file=await api('projects/project-1/attachments','POST',{requestId:crypto.randomUUID(),name:'example.pdf',mime:'application/pdf',dataBase64:btoa('%PDF-1.4\nSynthetic example\n%%EOF')});const bad=await api('projects/project-1/attachments','POST',{requestId:crypto.randomUUID(),name:'bad.svg',mime:'image/svg+xml',dataBase64:btoa('<svg/>')});return {saved,c,calendar,file,bad};});assert.equal(save.saved.status,200);assert.equal(save.c.status,200);assert.equal(save.calendar.status,200);assert.equal(save.file.status,200);assert.equal(save.bad.status,422);console.log('PASS device writes, calendar, validated file upload and active-content rejection');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.goto(base+'#project/project-1');await page.getByRole('heading',{name:'Persistent offline art station',exact:true}).waitFor();const files=await page.evaluate(async()=>{const list=await(await fetch('/api/projects/project-1/attachments')).json();const r=await fetch('/api/projects/project-1/attachments/'+list.items[0].id+'/download');return {status:r.status,text:await r.text()};});assert.equal(files.status,200);assert.match(files.text,/%PDF/);console.log('PASS offline cached shell, persisted record and attachment download');assert.deepEqual(errors,[]);console.log('PASS no uncaught browser errors');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
