import test from 'node:test';
import assert from 'node:assert/strict';
import {seed} from '../seed.mjs';
import {normalise,dispatch} from '../device-model.mjs';
import '../device-extensions.mjs';
import {validateBackup} from '../device-backups.mjs';

test('independent device standard payment decision and manager adjustment retain audited amounts through backup',async()=>{
 const data=normalise(seed({enriched:false})),call=(path,method='GET',body={})=>dispatch(data,path,method,body),id='project-1',path=`projects/${id}/lifecycle`,act=(action,data={})=>call(path,'PUT',{requestId:crypto.randomUUID(),version:call(`projects/${id}`).version,action,data});act('begin');act('assessmentDecision',{required:false,reason:'Synthetic triage'});act('assessmentReview',{approved:true,qualityReviewed:true,safetyReviewed:true,costsReviewed:true,reference:'Synthetic review',reviewedOn:'2026-01-01',notes:'Synthetic check'});
 const lines=[{type:'labour',description:'Synthetic service',quantityMilli:2000,unitPriceCents:3000},{type:'materials',description:'Synthetic component',quantityMilli:1000,unitPriceCents:100}],pricing={serviceHoursMilli:2000,serviceRateCents:5000,serviceChargeCents:6000,adjustmentReason:'Synthetic reduced charge',approvedBy:'Synthetic product manager',approvalReference:'Synthetic manager check',approvedOn:'2026-01-01',invoiceBeforeBuild:true,fundingUncertain:false,invoiceReason:'Synthetic funding-risk decision'};
 assert.throws(()=>act('quote',{lines,notes:''}),/manager|approval/);assert.throws(()=>act('quote',{lines,notes:'',pricing:{...pricing,adjustmentReason:''}}));assert.throws(()=>act('quote',{lines,notes:'',pricing:{...pricing,serviceChargeCents:10000}}));act('quote',{lines,notes:'Synthetic reviewed quote',pricing});assert.equal(call(path).state.quotes[0].totalCents,6100);assert.equal(call(path).state.quotes[0].pricing.baselineServiceChargeCents,10000);act('issueQuote',{quoteVersion:1,sentOn:'2026-01-01'});act('acceptQuote',{quoteVersion:1,acceptedBy:'Synthetic client',reference:'Synthetic acceptance',date:'2026-01-01'});
 const request={quoteVersion:1,reference:'Synthetic request',sentOn:'2026-01-01',instructions:'Synthetic access'},payment={quoteVersion:1,status:'paid',reference:'Synthetic Finance confirms payment',confirmedOn:'2026-01-01',notes:''};assert.equal(call(path).effectiveStage,'finance_clearance');assert.throws(()=>act('workRequest',request),/payment/);assert.throws(()=>act('financeClearance',{...payment,status:'exempt',notes:'Synthetic exception attempt'}),/payment/);act('financeClearance',payment);act('workRequest',request);act('work',{status:'in_progress',notes:'Synthetic paid work'});act('revise',{reason:'Synthetic revised scope'});assert.throws(()=>act('quote',{lines,notes:'',pricing:{...pricing,invoiceBeforeBuild:false}}));act('quote',{lines,notes:'Synthetic revision',pricing});act('issueQuote',{quoteVersion:2,sentOn:'2026-01-01'});act('acceptQuote',{quoteVersion:2,acceptedBy:'Synthetic client',reference:'Synthetic revised acceptance',date:'2026-01-01'});assert.throws(()=>act('workRequest',{...request,quoteVersion:2}),/payment/);
 assert.deepEqual((await validateBackup(data)).lifecycles[id],data.lifecycles[id]);const bad=JSON.parse(JSON.stringify(data));bad.lifecycles[id].quotes[0].pricing.approvedBy='Synthetic changed manager';await assert.rejects(validateBackup(bad),/recorded history/);
});
