import test from 'node:test';
import assert from 'node:assert/strict';
import {seed} from '../seed.mjs';
import {normalise,dispatch} from '../device-model.mjs';
import '../device-extensions.mjs';
import {validateBackup} from '../device-backups.mjs';
import {createFreedomWheelsDetails} from '../project-details-model.js';
import {applyLifecycle} from '../lifecycle-model.js';

test('independent device FW specifications and folder preserve older payloads and validated backups',async()=>{
 const data=normalise(seed({enriched:false})),call=(path,method='GET',body={})=>dispatch(data,path,method,body),path='projects/project-1/admin-details',initial=call(path),reference=call('projects/project-1').reference;
 const bike={...createFreedomWheelsDetails(),cycleType:'Trike',colour:'Synthetic blue',pedalClips:'Synthetic clips',linkedPedals:'Synthetic link',rearSteering:'Synthetic steering',handlebars:'Synthetic bars',backSupport:'Synthetic support',seat:'Synthetic seat'},folder='https://synthetic.sharepoint.com/sites/projects/SYNTHETIC-1';
 const payload=(record,extras={})=>({requestId:crypto.randomUUID(),version:record.version,programme:'FW',coordinatorAccountId:'',followUpOn:'2026-10-09',enquirySource:'Synthetic only',...extras});
 let saved=call(path,'PUT',payload(initial,{freedomWheels:bike,documentFolderUrl:folder,assessmentInstructions:'Synthetic assessment access'}));const oldBike=Object.fromEntries(['bikeMake','bikeSize','bikeSerialNumber','bikeSource','notes'].map(k=>[k,bike[k]]));saved=call(path,'PUT',payload(saved,{freedomWheels:oldBike}));assert.deepEqual(saved.freedomWheels,bike);assert.equal(saved.documentFolderUrl,folder);saved=call(path,'PUT',payload(saved));assert.deepEqual(saved.freedomWheels,bike);assert.equal(saved.documentFolderUrl,folder);assert.equal(saved.assessmentInstructions,'Synthetic assessment access');
 assert.throws(()=>call(path,'PUT',{...payload(saved),reference:'RENUMBER'}));assert.equal(call('projects/project-1').reference,reference);
 const life='projects/project-1/lifecycle',act=(action,data={})=>call(life,'PUT',{requestId:crypto.randomUUID(),version:call('projects/project-1').version,action,data}),lines=[{type:'materials',description:'Synthetic bike',quantityMilli:1000,unitPriceCents:100}];
 act('begin');act('assessmentDecision',{required:false,reason:'Synthetic triage'});act('assessmentReview',{approved:true,qualityReviewed:true,safetyReviewed:true,costsReviewed:true,reference:'Synthetic review',reviewedOn:'2026-01-01',notes:'Synthetic check'});act('quote',{lines,notes:''});act('issueQuote',{quoteVersion:1,sentOn:'2026-01-01'});act('acceptQuote',{quoteVersion:1,acceptedBy:'Synthetic client',reference:'Synthetic acceptance',date:'2026-01-01'});
 const finance={quoteVersion:1,status:'paid',reference:'Synthetic payment',confirmedOn:'2026-01-01',notes:''},request={quoteVersion:1,reference:'Synthetic request',sentOn:'2026-01-01',instructions:'Synthetic access'};assert.equal(call(life).workGate.allowed,false);assert.throws(()=>act('workRequest',request),/payment/);assert.throws(()=>act('financeClearance',{...finance,status:'exempt',notes:'Synthetic attempted exemption'}),/payment/);assert.throws(()=>call(path,'PUT',{...payload(call(path)),programme:'TAD'}));act('financeClearance',finance);act('workRequest',request);assert.equal(call(life).workGate.allowed,true);act('work',{status:'in_progress',notes:'Synthetic paid build'});
 const restored=await validateBackup(data);assert.deepEqual(restored.projectAdminDetails['project-1'].freedomWheels,bike);assert.equal(restored.projectAdminDetails['project-1'].documentFolderUrl,folder);assert.equal(restored.projectAdminDetails['project-1'].assessmentInstructions,'Synthetic assessment access');
 const bad=structuredClone(data);bad.projectAdminDetails['project-1'].documentFolderUrl='javascript:alert(1)';await assert.rejects(validateBackup(bad),/secure|https/);
 const badPayment=structuredClone(data);badPayment.lifecycles['project-1'].financeClearance.status='exempt';await assert.rejects(validateBackup(badPayment),/recorded history|payment received/);
});

test('independent old unmarked FW work keeps history while payment recovery authorises only new paid work',async()=>{
 const data=normalise(seed({enriched:false})),call=(path,method='GET',body={})=>dispatch(data,path,method,body),id='project-2',path=`projects/${id}/admin-details`,initial=call(path);
 call(path,'PUT',{requestId:crypto.randomUUID(),version:initial.version,programme:'FW',coordinatorAccountId:'',followUpOn:'2026-10-09',enquirySource:'Synthetic historical fitting'});
 let old=null;const context={programme:'FW',enforceFreedomWheelsPayment:false,at:'2026-01-01T09:00:00.000Z',projectStatus:'open',actor:{id:null,displayName:'Synthetic historical operator',role:'administrator'}},past=(action,data={})=>old=applyLifecycle(old,action,data,context),lines=[{type:'materials',description:'Synthetic bike',quantityMilli:1000,unitPriceCents:100}],acceptance={quoteVersion:1,acceptedBy:'Synthetic client',reference:'Synthetic acceptance',date:'2026-01-01'},request={quoteVersion:1,reference:'Synthetic request',sentOn:'2026-01-01',instructions:'Synthetic access'};
 past('begin');past('assessmentDecision',{required:false,reason:'Synthetic triage'});past('assessmentReview',{approved:true,qualityReviewed:true,safetyReviewed:true,costsReviewed:true,reference:'Synthetic review',reviewedOn:'2026-01-01',notes:'Synthetic check'});past('quote',{lines,notes:''});past('issueQuote',{quoteVersion:1,sentOn:'2026-01-01'});past('acceptQuote',acceptance);past('workRequest',request);past('work',{status:'in_progress',notes:'Synthetic historical work'});data.lifecycles[id]=old;
 const life=`projects/${id}/lifecycle`,act=(action,data={})=>call(life,'PUT',{requestId:crypto.randomUUID(),version:call(`projects/${id}`).version,action,data});assert.deepEqual((await validateBackup(data)).lifecycles[id],old);assert.equal(call(life).effectiveStage,'finance_clearance');assert.equal(call(life).workGate.allowed,false);assert.throws(()=>act('work',{status:'complete',notes:'Synthetic attempted build'}),/payment/);act('returnTo',{target:'client_acceptance',reason:'Synthetic pause to confirm payment'});act('acceptQuote',acceptance);act('financeClearance',{quoteVersion:1,status:'paid',reference:'Synthetic Finance paid',confirmedOn:'2026-01-01',notes:''});act('workRequest',request);assert.equal(call(life).workGate.allowed,true);assert.deepEqual(data.lifecycles[id].history.slice(0,old.history.length),old.history);assert.deepEqual((await validateBackup(data)).lifecycles[id],data.lifecycles[id]);
});
