import test from 'node:test';
import assert from 'node:assert/strict';
import {applyLifecycle} from '../lifecycle-model.js';
const context={at:'2026-09-24T01:00:00.000Z',programme:'FW',actor:{id:null,displayName:'Synthetic test',role:'administrator'}};
const apply=(s,action,data={},ctx=context)=>applyLifecycle(s,action,data,ctx);
function reviewed(){let s=apply(null,'begin');s=apply(s,'assessmentDecision',{required:false,reason:'Simple adjustment'});s=apply(s,'quote',{lines:[{type:'labour',description:'Adjustment',quantityMilli:1000,unitPriceCents:5000}],notes:''});return apply(s,'peerReview',{quoteVersion:1,reviewerId:'tech',approved:true,notes:'Reviewed'});}
function cleared(){let s=reviewed();s=apply(s,'acceptQuote',{quoteVersion:1,acceptedBy:'Synthetic client',reference:'Recorded',date:'2026-09-20'});return apply(s,'financeClearance',{quoteVersion:1,status:'exempt',reference:'Approved',notes:'Synthetic exemption',confirmedOn:'2026-09-20'});}
test('quote sent evidence is explicit, reviewed, single per revision and leaves gates intact',()=>{let s=reviewed();assert.equal(s.history.filter(e=>e.action==='issueQuote').length,0);assert.throws(()=>apply(s,'issueQuote',{quoteVersion:2,sentOn:'2026-09-20'}),/review/);for(const sentOn of ['2026-02-30','2026-09-25','1899-12-31'])assert.throws(()=>apply(s,'issueQuote',{quoteVersion:1,sentOn}));s=apply(s,'issueQuote',{quoteVersion:1,sentOn:'2026-09-20'});assert.equal(s.stage,'client_acceptance');assert.equal(s.acceptance,null);assert.equal(s.history.at(-1).programme,'FW');assert.throws(()=>apply(s,'issueQuote',{quoteVersion:1,sentOn:'2026-09-21'}),/already/);s=apply(s,'revise',{reason:'Updated requirement'});assert.equal(s.history.find(e=>e.action==='issueQuote').data.sentOn,'2026-09-20');});
test('delivery requires paired explicit evidence on completed FW work; legacy missing stays absent',()=>{const s=cleared();assert.equal(apply(s,'work',{status:'complete',notes:'Work finished'}).work.deliveredQuantity,undefined);for(const extra of [{deliveredOn:'2026-09-20'},{deliveredQuantity:2},{deliveredOn:'2026-09-20',deliveredQuantity:0},{deliveredOn:'2026-09-20',deliveredQuantity:1.5},{deliveredOn:'2026-09-20',deliveredQuantity:10001},{deliveredOn:'2026-09-25',deliveredQuantity:2}])assert.throws(()=>apply(s,'work',{status:'complete',notes:'Finished',...extra}));const input={status:'complete',notes:'Final delivery',deliveredOn:'2026-09-20',deliveredQuantity:2};assert.throws(()=>apply(s,'work',input,{...context,programme:'TAD'}),/Freedom Wheels/);assert.throws(()=>apply(s,'work',{...input,status:'in_progress'}),/completed/);let n=apply(s,'work',input);n=apply(n,'returnTo',{target:'work',reason:'Correct delivery total'});n=apply(n,'work',{...input,deliveredQuantity:3});assert.deepEqual(n.history.filter(e=>e.data.deliveredOn).map(e=>e.data.deliveredQuantity),[2,3]);assert.equal(n.history.findLast(e=>e.data.deliveredOn).data.deliveredQuantity,3);});
test('cancellation quantities are optional explicit non-negative bike totals retained after close/reopen',()=>{const s=cleared();assert.equal(apply(s,'cancel',{reason:'No undelivered bikes cancelled',cancelledQuantity:0}).cancellation.cancelledQuantity,0);assert.equal(apply(s,'cancel',{reason:'Unknown quantity'}).cancellation.cancelledQuantity,undefined);for(const cancelledQuantity of [-1,1.1,10001,'2',null])assert.throws(()=>apply(s,'cancel',{reason:'Withdrawn',cancelledQuantity}));assert.throws(()=>apply(s,'cancel',{reason:'Withdrawn',cancelledQuantity:2},{...context,programme:''}),/Freedom Wheels/);let n=apply(s,'cancel',{reason:'Withdrawn',cancelledQuantity:2});n=apply(n,'costReturn',{lines:[],notes:'No costs'});n=apply(n,'financeFinalise',{reference:'No charge',confirmedOn:'2026-09-24',notes:''});n=apply(n,'close',{reason:'Settled'});n=apply(n,'reopen',{reason:'New enquiry'});assert.equal(n.cancellation,null);assert.equal(n.history.find(e=>e.action==='cancel').data.cancelledQuantity,2);});

import {validateLifecycleBackup} from '../device-lifecycle-validation.mjs';
test('new reporting history and legacy histories replay without inferred fields',()=>{let s=cleared();s=apply(s,'issueQuote',{quoteVersion:1,sentOn:'2026-09-20'});s=apply(s,'work',{status:'complete',notes:'Final delivery',deliveredOn:'2026-09-21',deliveredQuantity:2});s=apply(s,'returnTo',{target:'work',reason:'Correct quantity'});s=apply(s,'work',{status:'complete',notes:'Correct final total',deliveredOn:'2026-09-21',deliveredQuantity:3});assert.deepEqual(validateLifecycleBackup(s),s);s=apply(s,'cancel',{reason:'Withdrawn remaining scope',cancelledQuantity:0});assert.deepEqual(validateLifecycleBackup(s),s);const bad=structuredClone(s);bad.history.find(e=>e.action==='issueQuote').data.sentOn='2999-01-01';assert.throws(()=>validateLifecycleBackup(bad),/future/);const {programme,...oldContext}=context;let legacy=apply(null,'begin',{},oldContext);legacy=apply(legacy,'assessmentDecision',{required:false,reason:'Old evidence'},oldContext);assert.deepEqual(validateLifecycleBackup(legacy),legacy);assert.equal(Object.hasOwn(legacy.history[0],'programme'),false);});
